<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Causality in randomised experiments | Modelling Criminological Data LAWS20452</title>
  <meta name="description" content="This is the draft for a book on using R for criminologists. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Causality in randomised experiments | Modelling Criminological Data LAWS20452" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the draft for a book on using R for criminologists. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Causality in randomised experiments | Modelling Criminological Data LAWS20452" />
  
  <meta name="twitter:description" content="This is the draft for a book on using R for criminologists. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Juanjo Medina and Reka Solymosi" />


<meta name="date" content="2020-01-31" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="a-first-lesson-about-r.html"/>
<link rel="next" href="data-visualisation-with-r.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Modelling Criminological Data</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html"><i class="fa fa-check"></i><b>1</b> A first lesson about R</a><ul>
<li class="chapter" data-level="1.1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#install-r-rstudio"><i class="fa fa-check"></i><b>1.1</b> Install R &amp; RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#open-up-and-explore-rstudio"><i class="fa fa-check"></i><b>1.2</b> Open up and explore RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#customising-the-rstudio-look"><i class="fa fa-check"></i><b>1.3</b> Customising the RStudio look</a></li>
<li class="chapter" data-level="1.4" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#getting-organised-r-projects"><i class="fa fa-check"></i><b>1.4</b> Getting organised: R Projects</a></li>
<li class="chapter" data-level="1.5" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#talk-to-your-computer"><i class="fa fa-check"></i><b>1.5</b> Talk to your computer</a></li>
<li class="chapter" data-level="1.6" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#more-on-packages"><i class="fa fa-check"></i><b>1.6</b> More on packages</a></li>
<li class="chapter" data-level="1.7" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#using-objects"><i class="fa fa-check"></i><b>1.7</b> Using objects</a></li>
<li class="chapter" data-level="1.8" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#more-on-objects"><i class="fa fa-check"></i><b>1.8</b> More on objects</a></li>
<li class="chapter" data-level="1.9" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#on-comments"><i class="fa fa-check"></i><b>1.9</b> On comments</a></li>
<li class="chapter" data-level="1.10" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#factors"><i class="fa fa-check"></i><b>1.10</b> Factors</a></li>
<li class="chapter" data-level="1.11" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#naming-conventions-for-objects-in-r"><i class="fa fa-check"></i><b>1.11</b> Naming conventions for objects in R</a></li>
<li class="chapter" data-level="1.12" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#dataframes"><i class="fa fa-check"></i><b>1.12</b> Dataframes</a></li>
<li class="chapter" data-level="1.13" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#exploring-data"><i class="fa fa-check"></i><b>1.13</b> Exploring data</a></li>
<li class="chapter" data-level="1.14" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#quitting-rstudio"><i class="fa fa-check"></i><b>1.14</b> Quitting RStudio</a></li>
<li class="chapter" data-level="1.15" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#lab-homework-activities-for-week-1"><i class="fa fa-check"></i><b>1.15</b> Lab homework activities for Week 1</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html"><i class="fa fa-check"></i><b>2</b> Causality in randomised experiments</a><ul>
<li class="chapter" data-level="2.1" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#causality-in-social-sciences"><i class="fa fa-check"></i><b>2.1</b> Causality in social sciences</a></li>
<li class="chapter" data-level="2.2" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#getting-data-thanks-to-reproducibility"><i class="fa fa-check"></i><b>2.2</b> Getting data thanks to reproducibility</a></li>
<li class="chapter" data-level="2.3" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#getting-a-sense-for-your-data"><i class="fa fa-check"></i><b>2.3</b> Getting a sense for your data</a><ul>
<li class="chapter" data-level="2.3.1" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#first-steps"><i class="fa fa-check"></i><b>2.3.1</b> First steps</a></li>
<li class="chapter" data-level="2.3.2" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#on-tibbles-and-labelled-vectors"><i class="fa fa-check"></i><b>2.3.2</b> On tibbles and labelled vectors</a></li>
<li class="chapter" data-level="2.3.3" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#turning-variables-into-factors-and-changing-the-labels"><i class="fa fa-check"></i><b>2.3.3</b> Turning variables into factors and changing the labels</a></li>
<li class="chapter" data-level="2.3.4" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#looking-for-missing-data-and-other-anomalies"><i class="fa fa-check"></i><b>2.3.4</b> Looking for missing data and other anomalies</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#data-wrangling-with-dplyr"><i class="fa fa-check"></i><b>2.4</b> Data wrangling with dplyr</a></li>
<li class="chapter" data-level="2.5" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#using-dplyr-single-verbs"><i class="fa fa-check"></i><b>2.5</b> Using dplyr single verbs</a></li>
<li class="chapter" data-level="2.6" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#using-dplyr-for-grouped-operations"><i class="fa fa-check"></i><b>2.6</b> Using dplyr for grouped operations</a></li>
<li class="chapter" data-level="2.7" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#making-comparisons-with-numerical-outcomes"><i class="fa fa-check"></i><b>2.7</b> Making comparisons with numerical outcomes</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html"><i class="fa fa-check"></i><b>3</b> Data visualisation with R</a><ul>
<li class="chapter" data-level="3.1" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#introduction"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#anatomy-of-a-plot"><i class="fa fa-check"></i><b>3.2</b> Anatomy of a plot</a></li>
<li class="chapter" data-level="3.3" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#what-graph-should-i-use"><i class="fa fa-check"></i><b>3.3</b> What graph should I use?</a></li>
<li class="chapter" data-level="3.4" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#visualising-numerical-variables-histograms"><i class="fa fa-check"></i><b>3.4</b> Visualising numerical variables: Histograms</a></li>
<li class="chapter" data-level="3.5" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#visualising-numerical-variables-density-plots"><i class="fa fa-check"></i><b>3.5</b> Visualising numerical variables: Density plots</a></li>
<li class="chapter" data-level="3.6" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#exploring-relationships-between-two-quantitative-variables-scatterplots"><i class="fa fa-check"></i><b>3.6</b> Exploring relationships between two quantitative variables: scatterplots</a></li>
<li class="chapter" data-level="3.7" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#scatterplots-conditioning-in-a-third-variable"><i class="fa fa-check"></i><b>3.7</b> Scatterplots conditioning in a third variable</a></li>
<li class="chapter" data-level="3.8" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#scatterplot-matrix"><i class="fa fa-check"></i><b>3.8</b> Scatterplot matrix</a></li>
<li class="chapter" data-level="3.9" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#titles-legends-and-themes-in-ggplot2"><i class="fa fa-check"></i><b>3.9</b> Titles, legends, and themes in ggplot2</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-carpentry.html"><a href="data-carpentry.html"><i class="fa fa-check"></i><b>4</b> Data Carpentry</a><ul>
<li class="chapter" data-level="4.1" data-path="data-carpentry.html"><a href="data-carpentry.html#introduction-1"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="data-carpentry.html"><a href="data-carpentry.html#a-template-for-your-assignment"><i class="fa fa-check"></i><b>4.2</b> A template for your assignment</a></li>
<li class="chapter" data-level="4.3" data-path="data-carpentry.html"><a href="data-carpentry.html#thinking-about-your-data-filtering-cases"><i class="fa fa-check"></i><b>4.3</b> Thinking about your data: filtering cases</a></li>
<li class="chapter" data-level="4.4" data-path="data-carpentry.html"><a href="data-carpentry.html#selecting-variables-using-dplyrselect"><i class="fa fa-check"></i><b>4.4</b> Selecting variables: using <code>dplyr::select</code></a></li>
<li class="chapter" data-level="4.5" data-path="data-carpentry.html"><a href="data-carpentry.html#creating-summated-scales"><i class="fa fa-check"></i><b>4.5</b> Creating summated scales</a></li>
<li class="chapter" data-level="4.6" data-path="data-carpentry.html"><a href="data-carpentry.html#collapsing-categories-in-character-variables"><i class="fa fa-check"></i><b>4.6</b> Collapsing categories in character variables</a></li>
<li class="chapter" data-level="4.7" data-path="data-carpentry.html"><a href="data-carpentry.html#working-with-apparently-cryptic-variable-names-and-levels"><i class="fa fa-check"></i><b>4.7</b> Working with apparently cryptic variable names and levels</a></li>
<li class="chapter" data-level="4.8" data-path="data-carpentry.html"><a href="data-carpentry.html#recoding-factors"><i class="fa fa-check"></i><b>4.8</b> Recoding factors</a></li>
<li class="chapter" data-level="4.9" data-path="data-carpentry.html"><a href="data-carpentry.html#understanding-missing-data"><i class="fa fa-check"></i><b>4.9</b> Understanding missing data</a></li>
<li class="chapter" data-level="4.10" data-path="data-carpentry.html"><a href="data-carpentry.html#exploring-dataframes-visually"><i class="fa fa-check"></i><b>4.10</b> Exploring dataframes visually</a></li>
<li class="chapter" data-level="4.11" data-path="data-carpentry.html"><a href="data-carpentry.html#further-resources"><i class="fa fa-check"></i><b>4.11</b> Further resources</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html"><i class="fa fa-check"></i><b>5</b> Foundations of statistical inference: confidence intervals</a><ul>
<li class="chapter" data-level="5.1" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#introduction-2"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#generating-random-data"><i class="fa fa-check"></i><b>5.2</b> Generating random data</a></li>
<li class="chapter" data-level="5.3" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#sampling-distributions-and-sampling-experiments"><i class="fa fa-check"></i><b>5.3</b> Sampling distributions and sampling experiments</a></li>
<li class="chapter" data-level="5.4" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#the-normal-distribution-and-confidence-intervals-with-known-standard-errors"><i class="fa fa-check"></i><b>5.4</b> The normal distribution and confidence intervals with known standard errors</a></li>
<li class="chapter" data-level="5.5" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#asymptotic-confidence-intervals-for-means-and-proportions-using-r"><i class="fa fa-check"></i><b>5.5</b> Asymptotic confidence intervals for means and proportions using R</a></li>
<li class="chapter" data-level="5.6" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#a-brief-intro-to-resampling-and-bootstraping"><i class="fa fa-check"></i><b>5.6</b> A brief intro to resampling and bootstraping</a></li>
<li class="chapter" data-level="5.7" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#what-about-comparisons-sampling-distribution-for-the-difference-of-two-means"><i class="fa fa-check"></i><b>5.7</b> What about comparisons? Sampling distribution for the difference of two means</a></li>
<li class="chapter" data-level="5.8" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#comparing-means-visually-by-using-error-bars-representing-confidence-intervals-inference-by-eye"><i class="fa fa-check"></i><b>5.8</b> Comparing means visually by using error bars representing confidence intervals: inference by eye</a></li>
<li class="chapter" data-level="5.9" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#homework-5.1"><i class="fa fa-check"></i><b>5.9</b> HOMEWORK 5.1</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><i class="fa fa-check"></i><b>6</b> Studying relationships between a categorical and a quantitative variable</a><ul>
<li class="chapter" data-level="6.1" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#the-logic-of-hypothesis-testing"><i class="fa fa-check"></i><b>6.1</b> The logic of hypothesis testing</a></li>
<li class="chapter" data-level="6.2" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#comparing-means-across-two-groups-the-t-test"><i class="fa fa-check"></i><b>6.2</b> Comparing means across two groups (the t test)</a></li>
<li class="chapter" data-level="6.3" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#what-does-a-significant-effect-mean"><i class="fa fa-check"></i><b>6.3</b> What does a significant effect mean?</a></li>
<li class="chapter" data-level="6.4" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#power-analysis"><i class="fa fa-check"></i><b>6.4</b> Power analysis</a></li>
<li class="chapter" data-level="6.5" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#comparing-means-across-several-groups-anova"><i class="fa fa-check"></i><b>6.5</b> Comparing means across several groups (ANOVA)</a><ul>
<li class="chapter" data-level="6.5.1" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#the-problem-with-multiple-comparisons"><i class="fa fa-check"></i><b>6.5.1</b> The problem with multiple comparisons</a></li>
<li class="chapter" data-level="6.5.2" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#anova"><i class="fa fa-check"></i><b>6.5.2</b> ANOVA</a></li>
<li class="chapter" data-level="6.5.3" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#checking-homogeneity-of-variance-and-dealing-with-unequal-spread"><i class="fa fa-check"></i><b>6.5.3</b> Checking homogeneity of variance and dealing with unequal spread</a></li>
<li class="chapter" data-level="6.5.4" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#checking-normality-and-dealing-with-problems"><i class="fa fa-check"></i><b>6.5.4</b> Checking normality and dealing with problems</a></li>
<li class="chapter" data-level="6.5.5" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#robust-anova"><i class="fa fa-check"></i><b>6.5.5</b> Robust ANOVA</a></li>
<li class="chapter" data-level="6.5.6" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#post-hoc-comparisons"><i class="fa fa-check"></i><b>6.5.6</b> Post Hoc Comparisons</a></li>
<li class="chapter" data-level="6.5.7" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#effect-size-for-anova"><i class="fa fa-check"></i><b>6.5.7</b> Effect size for ANOVA</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="studying-relationships-between-two-factors.html"><a href="studying-relationships-between-two-factors.html"><i class="fa fa-check"></i><b>7</b> Studying relationships between two factors</a><ul>
<li class="chapter" data-level="7.1" data-path="studying-relationships-between-two-factors.html"><a href="studying-relationships-between-two-factors.html#producing-cross-tabulations"><i class="fa fa-check"></i><b>7.1</b> Producing cross tabulations</a></li>
<li class="chapter" data-level="7.2" data-path="studying-relationships-between-two-factors.html"><a href="studying-relationships-between-two-factors.html#expected-frequencies-and-chi-square"><i class="fa fa-check"></i><b>7.2</b> Expected frequencies and Chi-Square</a></li>
<li class="chapter" data-level="7.3" data-path="studying-relationships-between-two-factors.html"><a href="studying-relationships-between-two-factors.html#residuals"><i class="fa fa-check"></i><b>7.3</b> Residuals</a></li>
<li class="chapter" data-level="7.4" data-path="studying-relationships-between-two-factors.html"><a href="studying-relationships-between-two-factors.html#gamma"><i class="fa fa-check"></i><b>7.4</b> Gamma</a></li>
<li class="chapter" data-level="7.5" data-path="studying-relationships-between-two-factors.html"><a href="studying-relationships-between-two-factors.html#odds-and-odd-ratios"><i class="fa fa-check"></i><b>7.5</b> Odds and odd ratios</a></li>
<li class="chapter" data-level="7.6" data-path="studying-relationships-between-two-factors.html"><a href="studying-relationships-between-two-factors.html#homework-7.1"><i class="fa fa-check"></i><b>7.6</b> HOMEWORK 7.1</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html"><i class="fa fa-check"></i><b>8</b> An introduction to regression</a><ul>
<li class="chapter" data-level="8.1" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#introduction-models-in-scientific-research"><i class="fa fa-check"></i><b>8.1</b> Introduction: models in scientific research</a></li>
<li class="chapter" data-level="8.2" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#motivating-regression"><i class="fa fa-check"></i><b>8.2</b> Motivating regression</a></li>
<li class="chapter" data-level="8.3" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#fitting-a-simple-regression-model"><i class="fa fa-check"></i><b>8.3</b> Fitting a simple regression model</a></li>
<li class="chapter" data-level="8.4" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#residuals-revisited-r-squared"><i class="fa fa-check"></i><b>8.4</b> Residuals revisited: R squared</a></li>
<li class="chapter" data-level="8.5" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#inference-with-regression"><i class="fa fa-check"></i><b>8.5</b> Inference with regression</a></li>
<li class="chapter" data-level="8.6" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#fitting-regression-with-categorical-predictors"><i class="fa fa-check"></i><b>8.6</b> Fitting regression with categorical predictors</a></li>
<li class="chapter" data-level="8.7" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#motivating-multiple-regression"><i class="fa fa-check"></i><b>8.7</b> Motivating multiple regression</a></li>
<li class="chapter" data-level="8.8" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#fitting-and-interpreting-a-multiple-regression-model"><i class="fa fa-check"></i><b>8.8</b> Fitting and interpreting a multiple regression model</a></li>
<li class="chapter" data-level="8.9" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#presenting-your-regression-results."><i class="fa fa-check"></i><b>8.9</b> Presenting your regression results.</a></li>
<li class="chapter" data-level="8.10" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#testing-conditional-hypothesis-interactions"><i class="fa fa-check"></i><b>8.10</b> Testing conditional hypothesis: interactions</a></li>
<li class="chapter" data-level="8.11" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#model-building-and-variable-selection"><i class="fa fa-check"></i><b>8.11</b> Model building and variable selection</a></li>
<li class="chapter" data-level="8.12" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#homework"><i class="fa fa-check"></i><b>8.12</b> HOMEWORK</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>9</b> Logistic regression</a><ul>
<li class="chapter" data-level="9.1" data-path="logistic-regression.html"><a href="logistic-regression.html#introduction-3"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="logistic-regression.html"><a href="logistic-regression.html#fitting-logistic-regression"><i class="fa fa-check"></i><b>9.2</b> Fitting logistic regression</a></li>
<li class="chapter" data-level="9.3" data-path="logistic-regression.html"><a href="logistic-regression.html#assessing-model-fit-i-deviance-and-pseudo-r-squared"><i class="fa fa-check"></i><b>9.3</b> Assessing model fit I: deviance and pseudo r squared</a></li>
<li class="chapter" data-level="9.4" data-path="logistic-regression.html"><a href="logistic-regression.html#assessing-model-fit-ii-confusion-matrix-and-roc-curves"><i class="fa fa-check"></i><b>9.4</b> Assessing model fit II: confusion matrix and ROC curves</a></li>
<li class="chapter" data-level="9.5" data-path="logistic-regression.html"><a href="logistic-regression.html#interactions"><i class="fa fa-check"></i><b>9.5</b> Interactions</a></li>
<li class="chapter" data-level="9.6" data-path="logistic-regression.html"><a href="logistic-regression.html#homework-1"><i class="fa fa-check"></i><b>9.6</b> HOMEWORK:</a></li>
<li class="chapter" data-level="9.7" data-path="logistic-regression.html"><a href="logistic-regression.html#further-resources-1"><i class="fa fa-check"></i><b>9.7</b> Further resources</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Modelling Criminological Data LAWS20452</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="causality-in-randomised-experiments" class="section level1">
<h1><span class="header-section-number">Chapter 2</span> Causality in randomised experiments</h1>
<div id="causality-in-social-sciences" class="section level2">
<h2><span class="header-section-number">2.1</span> Causality in social sciences</h2>
<p>In today’s session we will refresh themes you have explored in previous research methods courses, specifically causality. This is a central concept in empirical research. We often do research because we want to make causal inferences. We want to be in a position where we establish whether an intervention or a social process is causally linked to crime or some other relevant criminological outcome.</p>
<p>Making causal inferences often involves making comparisons. For example, between cases that have been subject to an intervention and cases that have not being subject to the causal process we are trying to investigate. But you should already know that not all kind of research comparisons are the same. In previous methods courses you must have discussed the differences between experimental and observational studies. This different kinds of research designs have a bearing on your ability to make causal inference.</p>
<p>Let’s think about a specific case so that this makes more sense. Is there discrimination against former offenders in the labor market? In other words, are offenders less likely to find employment after release because of prejudice among employers? Or can we say that the fact that former offenders are less likely to be in employment may be due to other factors? Perhaps, they are less skilled. Perhaps they have less social capital, people they know that can help them to get jobs or to learn about job opportunities. Perhaps, they are less interested in finding employment?</p>
<p>Only in comparisons when other things are equal you can make causal inferences. It would only be fair to compare John, an ex-offender with a high school degree and X number of personal connections and Y numbers of professional experience, with Peter, a non-ex offender, with the same educational and professional credentials than John (and everything else that matters when getting jobs also being equal between Peter and John).</p>
<p>How can you do that? How can you create situations when other things are equal? Well, that’s what courses in research design are oriented to teach you. What is important for you to remember is that the way data are generated, the way you do your study, will, of course, affect the kind of interpretations that you make from your statistical comparisons. And not all studies are created equal. Some research designs put you in a better position than others to make causal inference.</p>
<p>You should have learnt by now that the <a href="https://link.springer.com/article/10.1007/s11292-005-3538-2">“bronze” standard</a> for establishing causality in the social sciences is the randomised experiment. In a randomised trial, the researchers change the causal variable of interest for a group using something like a coin toss. As Angrist and Pischke (2015: xiii) highlight:</p>
<p><em>“By changing circumstances randomly, we make it highly likely that the variable of interest is unrelated to the many other factors determining the outcomes we mean to study… Random manipulation makes other things equal hold on average across the groups that did and did not experience manipulation”</em></p>
<p>So, say you want to establish whether arresting a perpetrator may have a deterrent effect on subsequent domestic abuse. You could randomise, basically use the equivalent of a lottery, to decide whether the police officer is going to arrest the perpetrator or not and then compare those you arrest with those you don’t arrest. Because you are randomising your treatment (the arrest) on average the treatment and the control group on the long run should be fairly similar and any differences you observe between them in the outcome of interest (domestic abuse recidivism) you could link it to your intervention -if you are interested in the answer to this you can read about it <a href="http://niccsa.org/uploads/file/f815aa02a0804639a53bb4a800952235/EFFECTSOFARRESTONINTIMATEPARTNERVIOLENCE.pdf">here</a>.</p>
<p>In this session we will look at data from a randomised trial that tried to establish whether there is discrimination in the labour market against former offenders. In doing so, we will also learn various functions used in R to read data, transform data, and to obtain summary statistics for groups. We will also very quickly introduce a plotting function used in R to generate graphics.</p>
</div>
<div id="getting-data-thanks-to-reproducibility" class="section level2">
<h2><span class="header-section-number">2.2</span> Getting data thanks to reproducibility</h2>
<p>Last week we introduced the notion of reproducible research and said that using and publishing code (particularly if using open source tools like R) is the way that <a href="https://osf.io/?gclid=EAIaIQobChMIq-jM6MuY2QIV7Z3tCh04vAycEAAYASAAEgLptPD_BwE">many researchers</a> around the world think that science ought to be done. This way of operating makes research more open, more credible, and more legitimate. It also means that we can more easily access the data used in published research. For this session we are going to use the data from <a href="https://academic.oup.com/qje/article/133/1/191/4060073">this</a> and <a href="https://pubs.aeaweb.org/doi/pdfplus/10.1257/aer.p20171003">this paper</a> study. In this research project, the authors tried to answer the question of whether criminal antecedents and other personal characteristics have an impact on access to employment. You can find more details about this work in <a href="https://www.probablecausation.com/podcasts/episode-8-amanda-agan">episode 8</a> of <em>Probable Causation</em>, the criminology podcast.</p>
<p><a href="http://economics.rutgers.edu/people/626-amanda-agan">Amanda Agan</a> and <a href="https://www.law.umich.edu/FacultyBio/Pages/FacultyBio.aspx?FacID=sbstarr">Sonja Starr</a> developed a randomised experiment in which they created 15,220 fake resumes randomly generating these critical characteristics (such as having a criminal record) and used these resumes to send online job applications to low-skill, entry level job openings in New Jersey and New York City. All the fictitious applicants were male and about 21 to 22 years old. These kind of experiments are very common among researchers that want to explore through these “audits” whether some personal characteristics are discriminated against in the labor market.</p>
<p>Because Amanda Agan and Sonja Starr conformed to reproducible standards when doing their research we can access this data from the <em>Harvard Dataverse</em> (a repository for open research data). Click <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/VPHMNT">here</a> to locate the data.</p>
<p><img src="imgs/harvarddataverse.PNG" /></p>
<p>In this page you can see a download section and some files that can be accessed. One of them contains analytic code pertaining to the study and the other contains the data. You also see a link called <strong>metadata</strong>. Metadata is data about data, it simply provides you with some information about the data. If you clink in metadata you will see at the bottom a reference to the software the authors used (STATA). So we know these files are in <a href="https://www.stata.com/">STATA</a> proprietary format. Let’s download the data file and then read the data into R.</p>
<p>You could just click “download” and then place the file in your project directory. Alternatively, and preferably, you may want to use code to make your whole work more reproducible. Think of it this way, every time you click or use drop down menus you are doing things that others cannot reproduce because there won’t be a written record of your steps. You will need though to do some clicking for finding out the required url you will use for writing your code. The file we want is the <code>AganStarrQJEData.dta</code>. Click in the name of this file. You will be taken to another webpage. On it you will see the download url. Copy and paste this url in your code below.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" title="1"><span class="co">#First, let&#39;s create an object with the link, paste the copied address here:</span></a>
<a class="sourceLine" id="cb61-2" title="2">data_url &lt;-<span class="st"> &quot;https://dataverse.harvard.edu/api/access/datafile/3036350&quot;</span></a></code></pre></div>
<p>This data file is a STATA .dta file in our working directory. To read STATA files we will need the <em>haven</em> package. This is a package developed for importing different kind of data files into R. If you don’t have it you will need to install it. And then load it.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" title="1"><span class="kw">library</span>(haven)</a>
<a class="sourceLine" id="cb62-2" title="2"><span class="co">#Now we can use the read_dta function, within this function we will</span></a>
<a class="sourceLine" id="cb62-3" title="3"><span class="co">#pass an argument, url, specifying to the read_dta function the need to</span></a>
<a class="sourceLine" id="cb62-4" title="4"><span class="co">#make a url connection. The url function takes as an argument the url</span></a>
<a class="sourceLine" id="cb62-5" title="5"><span class="co">#we are using and that we encoded in the data_url object in our case.</span></a>
<a class="sourceLine" id="cb62-6" title="6">banbox &lt;-<span class="st"> </span><span class="kw">read_dta</span>(<span class="kw">url</span>(data_url))</a></code></pre></div>
</div>
<div id="getting-a-sense-for-your-data" class="section level2">
<h2><span class="header-section-number">2.3</span> Getting a sense for your data</h2>
<div id="first-steps" class="section level3">
<h3><span class="header-section-number">2.3.1</span> First steps</h3>
<p>What is the first thing you need to ask yourself when you look at a dataset? Data are often too big to look at the whole thing. It is almost always impossible to eyeball the entire dataset and see what you have in terms of interesting patterns or potential problems. It is often a case of information overload and we want to be able to extract what is relevant and important about it. But where do you start? <a href="http://rex-analytics.com/data-analysis-questions-to-ask-the-first-time/">Here</a> you can find a brief but very useful overview put together by Steph de Silva. Read it before we carry on.</p>
<p><img src="imgs/firstlookatdata.jpg" /><!-- --></p>
<p>As Mara Averick (somebody you want to follow in twitter at <span class="citation">@dataanndme</span> if you want to be in top of R related resources) suggests this also makes for good relationship advice!</p>
<p><img src="imgs/relationships.png" /><!-- --></p>
<p>Here we are going to introduce a few functions that will help you to start making sense for what you have just downloaded. Summarising the data is the first step in any analysis and it is also used for finding out potential problems with the data. Regarding the latter you want to look out for: missing values; values outside the expected range (e.g., someone aged 200 years); values that seem to be in the wrong units; mislabeled variables; or variables that seem to be the wrong class (e.g., a quantitative variable encoded as a factor).</p>
<p>Lets start by the basic things you always look first in a datasets. You can see in the Environment window that banbox has 14813 observations (rows) of 62 variables (columns). You can also obtain this information using code. Here you want the <strong>DIM</strong>ensions of the dataframe (the number of rows and columns) so you use the <code>dim()</code> function:</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb63-1" title="1"><span class="kw">dim</span>(banbox)</a></code></pre></div>
<pre><code>## [1] 14813    62</code></pre>
<p>Looking at this information will help you to diagnose whether there was any trouble getting your data into R (e.g., imagine you know there should be more cases or more variables). You may also want to have a look at the names of the columns using the <code>names()</code> function. We will see the names of the variables.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb65-1" title="1"><span class="kw">names</span>(banbox)</a></code></pre></div>
<pre><code>##  [1] &quot;nj&quot;                   &quot;nyc&quot;                  &quot;app_date_d&quot;          
##  [4] &quot;pre&quot;                  &quot;post&quot;                 &quot;storeid&quot;             
##  [7] &quot;chain_id&quot;             &quot;center&quot;               &quot;crimbox&quot;             
## [10] &quot;crime&quot;                &quot;drugcrime&quot;            &quot;propertycrime&quot;       
## [13] &quot;ged&quot;                  &quot;empgap&quot;               &quot;white&quot;               
## [16] &quot;black&quot;                &quot;remover&quot;              &quot;noncomplier_store&quot;   
## [19] &quot;balanced&quot;             &quot;response&quot;             &quot;response_date_d&quot;     
## [22] &quot;daystoresponse&quot;       &quot;interview&quot;            &quot;cogroup_comb&quot;        
## [25] &quot;cogroup_njnyc&quot;        &quot;post_cogroup_njnyc&quot;   &quot;white_cogroup_njnyc&quot; 
## [28] &quot;ged_cogroup_njnyc&quot;    &quot;empgap_cogroup_njnyc&quot; &quot;box_white&quot;           
## [31] &quot;pre_white&quot;            &quot;post_white&quot;           &quot;white_nj&quot;            
## [34] &quot;post_remover_ged&quot;     &quot;post_ged&quot;             &quot;remover_ged&quot;         
## [37] &quot;post_remover_empgap&quot;  &quot;post_empgap&quot;          &quot;remover_empgap&quot;      
## [40] &quot;post_remover_white&quot;   &quot;post_remover&quot;         &quot;remover_white&quot;       
## [43] &quot;raerror&quot;              &quot;retail&quot;               &quot;num_stores&quot;          
## [46] &quot;avg_salesvolume&quot;      &quot;avg_num_employees&quot;    &quot;retail_white&quot;        
## [49] &quot;retail_post&quot;          &quot;retail_post_white&quot;    &quot;percblack&quot;           
## [52] &quot;percwhite&quot;            &quot;tot_crime_rate&quot;       &quot;nocrimbox&quot;           
## [55] &quot;nocrime_box&quot;          &quot;nocrime_pre&quot;          &quot;response_white&quot;      
## [58] &quot;response_black&quot;       &quot;response_ged&quot;         &quot;response_hsd&quot;        
## [61] &quot;response_empgap&quot;      &quot;response_noempgap&quot;</code></pre>
<p>As you may notice, these names may be hard to interpret. If you open the dataset in the data viewer of RStudio (using <code>View</code>) you will see that each column has a variable name and underneath a longer and more meaningful <strong>variable label</strong> that tells you what each variable means.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb67-1" title="1"><span class="kw">View</span>(banbox)</a></code></pre></div>
</div>
<div id="on-tibbles-and-labelled-vectors" class="section level3">
<h3><span class="header-section-number">2.3.2</span> On tibbles and labelled vectors</h3>
<p>You also want to understand what the banbox object actually is. You can do that using the <code>class()</code> function:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" title="1"><span class="kw">class</span>(banbox)</a></code></pre></div>
<pre><code>## [1] &quot;tbl_df&quot;     &quot;tbl&quot;        &quot;data.frame&quot;</code></pre>
<p>What does <code>tbl</code> stands for? It refers to <strong>tibbles</strong>. This is essentially a new type of data structure introduced into R. Tibbles <em>are</em> data frames, but a particular type. Not all data frames we encounter in R are tibbles.</p>
<p>The R language has been around for a while and sometimes things that made sense a couple of decades ago, make less sense now. A number of programmers are trying to create code that is more modern and more useful today. They are doing this by introducing a set of packages that speak to each other in order to modernise R without breaking existing code. You can think of it as an easier and more efficient modern dialect of R. This set of packages is called the <strong>tidyverse</strong>. Tibbles are dataframes that have been optimised to be used with this new set of packages. You can read a bit more about tibbles <a href="http://r4ds.had.co.nz/tibbles.html">here</a>.</p>
<p>You can also look at the class of each individual column. As discussed, class of the variable lets us know, for example, if its an integer (number), character, or factor.</p>
<p>To get the class of one variable, you pass it to the <code>class()</code> function. For example:</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" title="1"><span class="kw">class</span>(banbox<span class="op">$</span>crime)</a></code></pre></div>
<pre><code>## [1] &quot;haven_labelled&quot;</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" title="1"><span class="kw">class</span>(banbox<span class="op">$</span>num_stores)</a></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<p>We talked about numeric vectors in week one. It is simply a collection of numbers. But what is a labelled vector? This is a new type of vector introduced by the <em>haven</em> package. <strong>Labelled vectors</strong> are categorical variables that have labels. Go to the <em>Environment</em> panel and left click in the banbox object. This should open the data browser in the top left quadrant of RStudio.</p>
<p><img src="imgs/dataview_causality.png" /></p>
<p>If you look carefully you will see that the various columns that include categorical variables only contain numbers. In many statistical environments, such as STATA or SPSS, this is a common standard. The variables have a numeric value for each observation and then each of these numeric values is associated with a label. This kind of made sense when computer memory was an issue - for this was an efficient way of saving resources. It also made manual data input quicker. These days it makes perhaps less sense. But labelled vectors give you a chance to reproduce data from other statistical environments without losing any fidelity in the import process. See what happens if we try to summarise this labelled vector. We will use the <code>table()</code> to provide a count of observations on the various valid values of the <em>crime</em> variable. It is a function to obtain your frequency distribution.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" title="1"><span class="kw">table</span>(banbox<span class="op">$</span>crime)</a></code></pre></div>
<pre><code>## 
##    0    1 
## 7323 7490</code></pre>
<p>So, we see that we have 7490 observations classed as 1 and 7323 classed as 2. If only we knew what those numbers represent! Well, we actually do. We will use the <code>attributes()</code> function to see the different “compartments”" within your “box”, your object.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb76-1" title="1"><span class="kw">attributes</span>(banbox<span class="op">$</span>crime)</a></code></pre></div>
<pre><code>## $label
## [1] &quot;Applicant has Criminal Record&quot;
## 
## $format.stata
## [1] &quot;%9.0g&quot;
## 
## $class
## [1] &quot;haven_labelled&quot;
## 
## $labels
## No Crime    Crime 
##        0        1</code></pre>
<p>So this object has different compartments. The first one is called label and it provides a description of what the variable measures. This is what you saw in the RStudio data viewer earlier. The second compartment explains the original format in which it was. The third one identifies the class of the vector. Whereas the final one, <em>labels</em>, provides the labels that allows us to identify what the meaning of 0 and 1 mean in this context.</p>
</div>
<div id="turning-variables-into-factors-and-changing-the-labels" class="section level3">
<h3><span class="header-section-number">2.3.3</span> Turning variables into factors and changing the labels</h3>
<p>Last week we said that many R functions expect factors when you have categorical data, so typically after you import data into R you may want to coerce your labelled vectors into factors. To do that you need to use the <code>as_factor()</code> function of the <em>haven</em> package. Let’s see how we do that.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb78-1" title="1"><span class="co">#This code asks R to create a new column in your banbox tibble</span></a>
<a class="sourceLine" id="cb78-2" title="2"><span class="co">#that is going to be called crime_f. Typically, when you alter</span></a>
<a class="sourceLine" id="cb78-3" title="3"><span class="co">#variables you can to create a new one so that the original gets</span></a>
<a class="sourceLine" id="cb78-4" title="4"><span class="co">#preserved in case you do something wrong. Then we use the</span></a>
<a class="sourceLine" id="cb78-5" title="5"><span class="co">#as_factor() function to explain to R that what we want to do</span></a>
<a class="sourceLine" id="cb78-6" title="6"><span class="co">#is to get the original crime variable and mutate it into </span></a>
<a class="sourceLine" id="cb78-7" title="7"><span class="co">#a factor, this resulting factor is what will be stored in</span></a>
<a class="sourceLine" id="cb78-8" title="8"><span class="co">#the new column.</span></a>
<a class="sourceLine" id="cb78-9" title="9">banbox<span class="op">$</span>crime_f &lt;-<span class="st"> </span><span class="kw">as_factor</span>(banbox<span class="op">$</span>crime)</a></code></pre></div>
<p>You will see now that you have 63 variables in your dataset, look at the environment to check. Let’s explore the new variable we have created (you can also look for the new variable in the data browser and see how it looks different to the original crime variable):</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb79-1" title="1"><span class="kw">class</span>(banbox<span class="op">$</span>crime_f)</a></code></pre></div>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb81-1" title="1"><span class="kw">table</span>(banbox<span class="op">$</span>crime_f)</a></code></pre></div>
<pre><code>## 
## No Crime    Crime 
##     7323     7490</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb83-1" title="1"><span class="kw">attributes</span>(banbox<span class="op">$</span>crime_f)</a></code></pre></div>
<pre><code>## $levels
## [1] &quot;No Crime&quot; &quot;Crime&quot;   
## 
## $class
## [1] &quot;factor&quot;
## 
## $label
## [1] &quot;Applicant has Criminal Record&quot;</code></pre>
<p>So far we have a looked at single columns in your dataframe one at the time. But there is a way that you can apply a function to all elements of a vector (list or dataframe). You can use the functions <code>sapply()</code>, <code>lapply()</code>, and <code>mapply()</code> . To find out more about when to use each one see <a href="https://www.r-bloggers.com/using-apply-sapply-lapply-in-r/">here</a>.</p>
<p>For example, we can use the <code>lapply()</code> function to look at each column and get its class. To do so, we have to pass two arguments to the <code>lapply()</code> function, the first is the name of the dataframe, to tell it what to look through, and the second is the function we want it to apply to every column of that function.</p>
<p>So we want to type “lapply(” + “name of dataframe” + “,” + “name of function” + “)”</p>
<p>Which is:</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb85-1" title="1"><span class="kw">lapply</span>(banbox, class)</a></code></pre></div>
<p>As you can see many variables are classed as labelled. This is common with survey data. Many of the questions in social surveys measure the answers as categorical variables (e.g., these are nominal or ordinal level measures). In fact, with this dataset there are many variables that are encoded as numeric that really aren’t. Welcome to real world data, where things can be a bit messy and need tidying!</p>
<p>See for example the variable black:</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb86-1" title="1"><span class="kw">class</span>(banbox<span class="op">$</span>black)</a></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb88-1" title="1"><span class="kw">table</span>(banbox<span class="op">$</span>black)</a></code></pre></div>
<pre><code>## 
##    0    1 
## 7406 7407</code></pre>
<p>We know that this variable measures whether someone is black or not. When people use 0 and 1 to code binary responses, typically they use a 1 to denote a positive response, a yes. So, I think it is fair to assume that a 1 here means the respondent is black. Because this variable is of class numeric we cannot simply use as_factor to assign the pre-existing labels and create a new factor. In this case we don’t have preexisting labels, since this is not a labelled vector. So what can we do to tidy this variable? We’ll we need to do some further work.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb90-1" title="1"><span class="co">#We will use a slightly different function as.factor()</span></a>
<a class="sourceLine" id="cb90-2" title="2">banbox<span class="op">$</span>black_f &lt;-<span class="st"> </span><span class="kw">as.factor</span>(banbox<span class="op">$</span>black)</a>
<a class="sourceLine" id="cb90-3" title="3"><span class="co">#You can check that the resulting column is a factor</span></a>
<a class="sourceLine" id="cb90-4" title="4"><span class="kw">class</span>(banbox<span class="op">$</span>black_f)</a></code></pre></div>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb92-1" title="1"><span class="co">#But if you print the frequency distribution you will see the</span></a>
<a class="sourceLine" id="cb92-2" title="2"><span class="co">#data are still presented in relation to 0 and 1</span></a>
<a class="sourceLine" id="cb92-3" title="3"><span class="kw">table</span>(banbox<span class="op">$</span>black_f)</a></code></pre></div>
<pre><code>## 
##    0    1 
## 7406 7407</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb94-1" title="1"><span class="co">#You can use the levels function to see the levels, the </span></a>
<a class="sourceLine" id="cb94-2" title="2"><span class="co">#categories, in your factor</span></a>
<a class="sourceLine" id="cb94-3" title="3"><span class="kw">levels</span>(banbox<span class="op">$</span>black_f)</a></code></pre></div>
<pre><code>## [1] &quot;0&quot; &quot;1&quot;</code></pre>
<p>So, all we have done is create a new column that is a factor but still refers to 0 and 1. If we assume (rightly) that 1 mean black we have 7407 black applicants. Of course, it makes sense we only get 0 and 1 here. What else could R do? This is not a labelled vector, so there is no way for R to know that 0 and 1 mean anything other than 0 and 1, which is why those are the levels is using. But now that we have the factor we can rename those levels. We can use the following code to do just that:</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb96-1" title="1"><span class="co">#We are using the levels function to access them and change</span></a>
<a class="sourceLine" id="cb96-2" title="2"><span class="co">#them to the levels we specify with the c() function. Be</span></a>
<a class="sourceLine" id="cb96-3" title="3"><span class="co">#careful here, because the order we specify here will map </span></a>
<a class="sourceLine" id="cb96-4" title="4"><span class="co">#out to the order of the existing levels. So given that 1 is </span></a>
<a class="sourceLine" id="cb96-5" title="5"><span class="co">#black and black is the second level (as shown when printing</span></a>
<a class="sourceLine" id="cb96-6" title="6"><span class="co">#the results above) you want to make sure that in the c()</span></a>
<a class="sourceLine" id="cb96-7" title="7"><span class="co">#you write black as the second level.</span></a>
<a class="sourceLine" id="cb96-8" title="8"><span class="kw">levels</span>(banbox<span class="op">$</span>black_f) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;White&quot;</span>, <span class="st">&quot;Black&quot;</span>)</a>
<a class="sourceLine" id="cb96-9" title="9"><span class="kw">table</span>(banbox<span class="op">$</span>black_f)</a></code></pre></div>
<pre><code>## 
## White Black 
##  7406  7407</code></pre>
<p>This gives you an idea of the kind of transformations you often want to perform to make your data more useful for your purposes. But let’s keep looking at functions you can use to explore your dataset.</p>
</div>
<div id="looking-for-missing-data-and-other-anomalies" class="section level3">
<h3><span class="header-section-number">2.3.4</span> Looking for missing data and other anomalies</h3>
<p>You can, for example, use the <code>head()</code> function if you just want to visualise the values for the first few cases in your dataset. The next code for example ask for the values for the first two cases. If you want a different number to be shown you just need to change the number you are passing as an argument.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb98-1" title="1"><span class="kw">head</span>(banbox, <span class="dv">2</span>)</a></code></pre></div>
<p>In the same way you could look at the last two cases in your dataset using <code>tail()</code>:</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb99-1" title="1"><span class="kw">tail</span>(banbox, <span class="dv">2</span>)</a></code></pre></div>
<p>It is good practice to do this to ensure R has read the data correctly and there’s nothing terribly wrong with your dataset. If you have access to STATA you can open the original file in STATA and check if there are any discrepancies, for example. Glimpsing your data in this way can also give you a first impression for what the data looks like.</p>
<p>One thing you may also want to do is to see if there are any <strong>missing values</strong>. For that we can use the <code>is.na()</code> function. Missing values in R are coded as NA. The code below, for example, asks for NA values for the variable <em>response_black</em> in the <em>banbox</em> object for observations 1 to 10:</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb100-1" title="1"><span class="kw">is.na</span>(banbox<span class="op">$</span>response_black[<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>])</a></code></pre></div>
<pre><code>##  [1] FALSE  TRUE  TRUE FALSE FALSE  TRUE  TRUE  TRUE FALSE  TRUE</code></pre>
<p>The result is a logical vector that tells us if it is true that there is missing (NA) data for each of those first ten observations. You can see that there are 6 observations out of those 10 that have missing values for this variable.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb102-1" title="1"><span class="kw">sum</span>(<span class="kw">is.na</span>(banbox<span class="op">$</span>response_black)) </a></code></pre></div>
<pre><code>## [1] 7406</code></pre>
<p>This is asking R to sum how many cases are TRUE NA in this variable. When reading a logical vector as the one we are creating, R will treat the FALSE elements as 0s and the TRUE elements as 1s. So basically the sum() function will count the number of TRUE cases returned by the is.na() function.</p>
<p>You can use a bit of a hack to get the proportion of missing cases instead of the count:</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb104-1" title="1"><span class="kw">mean</span>(<span class="kw">is.na</span>(banbox<span class="op">$</span>response_black))</a></code></pre></div>
<pre><code>## [1] 0.4999662</code></pre>
<p>This code is exploiting the mathematical fact that the mean of binary outcomes (0 or 1) gives you the proportion of ones in your data. As a rule of thumb, if you see more than 5% of the cases declared as NA, you need to start thinking about the implications of this. Beware of formulaic application of rules of thumb such as this though! In this case, we know that 49%% of the observations have missing values in this variable. When you see things like this the first thing to do is to look at the codebook or documentation to try to get some clues as to why there are so many missing cases. With survey data you often have questions that are simply not asked to everybody, so it’s not necessarily that something went very wrong with the data collection, but simply that the variable in question was only used with a subset of the sample. And that, therefore, any analysis you do using this question will only relate to that particular subset of cases.</p>
<p>There is a whole field of statistics devoted to doing analysis when missing data is a problem. R has extensive capabilities for dealing with missing data -see for example <a href="http://www.crcpress.com/product/isbn/9781439868249">here</a>. For the purpose of this introductory course, however, we only explain how to do analysis that ignore missing data. This is often referred to a <strong>full/complete case analysis</strong>, because you only use observations for which you have full information in all the variables you employ. You would cover techniques for dealing with this sort of issues in more advanced courses.</p>
</div>
</div>
<div id="data-wrangling-with-dplyr" class="section level2">
<h2><span class="header-section-number">2.4</span> Data wrangling with dplyr</h2>
<p>The data analysis workflow has a number of stages. The diagram below (produced by Hadley Wickham) is a nice illustration of this process:</p>
<p><img src="imgs/data-science-explore.png" /></p>
<p>We have started to see different ways of bringing data into R. And we have also started to see how we can explore our data. It is now time we start discussing one of the following stages, <strong>transform</strong>. A good deal of time and effort in data analysis is devoted to this. You get your data and then you have to do some transformations to it so that you can answer the questions you want to address in your research. We have already seen, for example, how to turn variables into factors, but there are other things you may want to do.</p>
<p>R offers a great deal of flexibility in how to transform your data, Here we are going to illustrate some of the functionality of the <em>dplyr</em> package for data carpentry (a term people use to refer to this kind of operations). This package is part of the tydiverse and it aims to provide a friendly and modern take on how to work with dataframes (or tibbles) in R. It offers, as the authors of the package put it, “a flexible grammar of data manipulation”.</p>
<p>Dplyr aims to provide a function for each basic verbs of data manipulation:</p>
<ul>
<li><code>*filter()*</code> to select cases based on their values.</li>
<li><code>*arrange()*</code> to reorder the cases.</li>
<li><code>*select()*</code> and <code>*rename()*</code> to select variables based on their names.</li>
<li><code>*mutate()*</code> and <code>*transmute()*</code> to add new variables that are functions of existing variables.</li>
<li><code>*summarise()*</code> to condense multiple values to a single value.</li>
<li><code>*sample_n()*</code> and <code>*sample_frac()*</code> to take random samples.</li>
</ul>
<p>In this session we will introduce and practice some of these. But we won’t have time to cover everything. There is, however, a very nice set of vignettes for this package in the help files, so you can try to go through those if you want a greater degree of detail or more practice.</p>
<p>Now let’s load the package:</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb106-1" title="1"><span class="kw">library</span>(dplyr)</a></code></pre></div>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<p>Notice that when you run this package you get a series of warnings in the conseole. It is telling us that some functions from certain packages are being “masked”. One the things with a language like R is that sometimes packages introduce functions that have the same name than others that are already loaded into your session. When that happens the newly loaded ones will over-ride the previous ones. You can still use them but you will have to refer to them explicitly. Otherwise R will assume you are using the function most recently loaded:</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb110-1" title="1"><span class="co">#Example:</span></a>
<a class="sourceLine" id="cb110-2" title="2"><span class="co">#If you use load dplyr and then invoke the *filter()* function</span></a>
<a class="sourceLine" id="cb110-3" title="3"><span class="co">#R will assume you are using the filter function from dplyr</span></a>
<a class="sourceLine" id="cb110-4" title="4"><span class="co">#rather than the *filter()* function that exist in the *stats*</span></a>
<a class="sourceLine" id="cb110-5" title="5"><span class="co">#package, which is part of the basic installation of R. If </span></a>
<a class="sourceLine" id="cb110-6" title="6"><span class="co">#after loading dplyr you want to use the filter function from</span></a>
<a class="sourceLine" id="cb110-7" title="7"><span class="co">#the stats package you will have to invoke it like this:</span></a>
<a class="sourceLine" id="cb110-8" title="8">stats<span class="op">::</span><span class="kw">filter</span>()</a>
<a class="sourceLine" id="cb110-9" title="9"><span class="co">#Notice the grammar, first you write the name of the package,</span></a>
<a class="sourceLine" id="cb110-10" title="10"><span class="co">#then colon twice, and then the name of the function. Don&#39;t </span></a>
<a class="sourceLine" id="cb110-11" title="11"><span class="co">#run this code. You would need to pass some valid arguments</span></a>
<a class="sourceLine" id="cb110-12" title="12"><span class="co">#for this to produce meaningful results.</span></a></code></pre></div>
</div>
<div id="using-dplyr-single-verbs" class="section level2">
<h2><span class="header-section-number">2.5</span> Using dplyr single verbs</h2>
<p>One of the first operations you may want to carry out when working with dataframes is to subset them based on values of particular variables. Say we want to replicate the results reported by Agan and Starr in 2017. In this earlier paper, these researchers only used data from the period prior to the introduction of Ban the Box legislation and only used data from businesses that asked about criminal records in their online applications. How can we recreate this dataset?</p>
<p>For this kind of operations we use the <code>filter()</code> function. Like all single verbs in dplyr, the first argument is the tibble (or data frame). The second and subsequent arguments refer to variables within that data frame, selecting rows where the expression is TRUE.</p>
<p>Ok, so if we look at the dataset we can see that there is a variable called “crimbox” that identifies applications that require information about criminal antecedents and there is a variable called “pre” that identifies whether the application was sent before the legislation was introduced. In this dataset the value 1 is being used to denote positive responses. So, if we want to create the 2017 dataset we would start by selecting only data where the value in these two variables equals 1 as shown below.</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb111-1" title="1"><span class="co">#We will store the results of filtering the data in a new </span></a>
<a class="sourceLine" id="cb111-2" title="2"><span class="co">#object that I am calling aer (short for the name of the </span></a>
<a class="sourceLine" id="cb111-3" title="3"><span class="co">#journal in which the paper was published)</span></a>
<a class="sourceLine" id="cb111-4" title="4"></a>
<a class="sourceLine" id="cb111-5" title="5">aer2017&lt;-<span class="st"> </span><span class="kw">filter</span>(banbox, crimbox <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, pre <span class="op">==</span><span class="st"> </span><span class="dv">1</span>)</a></code></pre></div>
<p>Notice that the number of cases equals the number of cases reported by the authors in their 2017 paper. That’s cool! So far we are replicating with same results.</p>
<p>You may have noticed in the code above that I wrote “==”" instead of “=”. Logical operators in R are not written exactly the same way than in normal practice. Keep this in mind when you get error messages from running your code. Often the source of your error may be that you are writing the logical operators the wrong way (as far as R is concerned). Look <a href="https://www.statmethods.net/management/operators.html">here</a> for valid logic operators in R.</p>
<p>Sometimes you may want to select only a few variables. Earlier we said that real life data may have hundreds of variables and only a few of those may be relevant for your analysis. Say you only want “crime”, “ged” (a ged is a high school equivalence diploma rather than a proper high school diploma and is sometimes seen as inferior), “empgap” (a gap year on employment), “black_f”, “response”, and “daystoresponse” from this dataset. For this kind of operations you use the <code>select()</code> function.</p>
<p>The syntax of this function is easy. First we name the dataframe object (“aer2017”) and then we list the variables. The order in which we list the variables within the select function will determine the order in which those columns appear in the new dataframe we are creating. So this is a handy function to use if you want to change the order of your columns for some reason. Since I am pretty confident I am not making a mistake I will transform the original “aer2017” tibble rather than creating an entirely new object.</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb112-1" title="1">aer2017 &lt;-<span class="st"> </span><span class="kw">select</span>(aer2017, crime, ged, empgap, black_f, response, daystoresponse)</a></code></pre></div>
<p>If you now look at the global environment you will see that the “aer2017” tibble has reduced in size and now only has 6 columns. If you view the data you will see these are the 6 variables we selected.</p>
</div>
<div id="using-dplyr-for-grouped-operations" class="section level2">
<h2><span class="header-section-number">2.6</span> Using dplyr for grouped operations</h2>
<p>So far we have used <code>dplyr</code> single verbs for ungrouped operations. But we can also use some of the functionality of <code>dplyr</code> for obtaining answers to questions that relate to groups of cases within our dataframe. Imagine that you want to know if applicants with a criminal record are less likely to receive a positive response from employers. How could you figure that one out? For answering this kind of questions we can use the <code>group_by()</code> function in conjunction with other <code>dplyr</code> functions. In particular we are going to look at the <code>summarise</code> function.</p>
<p>First we group the observations by criminal record in a new object, by using as_factor in the call to the crime variable the results will be labelled later on (even though we are not changing the crime variable in the aer2017 dataframe. Keep in mind we are using as_factor because the column crime is a labelled vector rather than a factor or a character vector, and we do this to aid interpretation (it is easier to
interpret labels than 0 and 1).</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb113-1" title="1">by_antecedents &lt;-<span class="st"> </span><span class="kw">group_by</span>(aer2017, <span class="kw">as_factor</span>(crime))</a>
<a class="sourceLine" id="cb113-2" title="2"></a>
<a class="sourceLine" id="cb113-3" title="3"><span class="co">#Then we run the summarise function to provide some useful</span></a>
<a class="sourceLine" id="cb113-4" title="4"><span class="co">#summaries of the groups we are using: the number of cases</span></a>
<a class="sourceLine" id="cb113-5" title="5"><span class="co">#and the mean of the response variable</span></a>
<a class="sourceLine" id="cb113-6" title="6">results &lt;-<span class="st"> </span><span class="kw">summarise</span>(by_antecedents,</a>
<a class="sourceLine" id="cb113-7" title="7">  <span class="dt">count =</span> <span class="kw">n</span>(),</a>
<a class="sourceLine" id="cb113-8" title="8">  <span class="dt">outcome =</span> <span class="kw">mean</span>(response, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</a>
<a class="sourceLine" id="cb113-9" title="9"><span class="co">#autoprint the results stored in the newly created object</span></a>
<a class="sourceLine" id="cb113-10" title="10">results</a></code></pre></div>
<pre><code>## # A tibble: 2 x 3
##   `as_factor(crime)` count outcome
##   &lt;fct&gt;              &lt;int&gt;   &lt;dbl&gt;
## 1 No Crime            1319  0.136 
## 2 Crime               1336  0.0846</code></pre>
<p>Let’s look at the code in the summarise function above. First we are asking R to place the results in an object we are calling “results”. Then we are specifying that we want to group the data in the way we specified in our <code>group_by()</code> function before, that is by criminal record. Then we pass two arguments. Each of these arguments is creating a new variable in the resulting object called “results”. The first variable we are creating is called “<em>count</em>” by saying this equals “n()” we are specifying to R that this new variable simply counts the number of cases in each of the grouping categories. The second variable we are creating is called “<em>outcome</em>” and to compute this variable we are asking R to compute the mean of the variable response for each of the two groups of applicants defined in “by_antecedents” (those with records, those without). Remember that the variable response in the “aer2017” dataframe was coded as numeric variable, even though in truth is categorical in nature (there was a response, or not, from the employers). It doesn’t really matter. Taking the mean of a binary variable in this case is mathematically equivalent to computing a proportion as we discussed earlier.</p>
<p>So, what we see here is that about 13.6% of applicants with no criminal record received a positive response from the employers, whereas only 8% of those with criminal records did receive such a response. Given that the assignation of a criminal record was randomised to the applicants, there’s a pretty good chance that no other <a href="https://en.wikipedia.org/wiki/Confounding"><strong>confounders</strong></a> are influencing this outcome. And that is the beauty of randomised experiments. You may be in a position to make stronger claims about your results.</p>
<p><strong>HOMEWORK 1:</strong>
<em>Use what we have learned so far to see if there is an interaction effect between race and criminal records. That is, what would happen if we compare 4 groups: whites with no records, whites with records, blacks with no records, and blacks with records. What do you think? Is there an interaction effect? In other words, is the impact of having a criminal record more accentuated for either of the two racial groups?</em></p>
</div>
<div id="making-comparisons-with-numerical-outcomes" class="section level2">
<h2><span class="header-section-number">2.7</span> Making comparisons with numerical outcomes</h2>
<p>We have been looking at relationships so far between categorical variables, specifically between having a criminal record (yes or no), race (black or white), and receiving a positive response from employers (yes or no). Often we may be interested in looking at the impact of a factor on a numerical outcome. In the banbox object we have such an outcome measured by the researchers. The variable “daystoresponse” tells us how long it took the employers to provide a positive response. Let’s look at this variable:</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb115-1" title="1"><span class="kw">summary</span>(banbox<span class="op">$</span>daystoresponse)</a></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##    0.00    3.00   10.00   19.48   28.00  153.00   14361</code></pre>
<p>The <code>summary()</code> function provides some useful stats for numerical variables. We obtain the minimum and maximum value, the 25th percentile, the median, the mean, the 75th percentile, and the number of missing data (NA). You can see the number of missing data here is massive. Most cases have missing data on this variable. Clearly this is a function of, first and foremost, the fact that the number of days to receive a positive response will only be collected in cases where there was a positive response! But even accounting for that, it is clear that this information is also missing in many cases that received a positive response. So given all of this, we need to be very careful when interpreting this variable. Yet, because it is the only numeric variable here we will use it to illustrate some handy functions.</p>
<p>We could do as before and get results by groups. Let’s look at the impact of race on days to response:</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb117-1" title="1">by_race &lt;-<span class="st"> </span><span class="kw">group_by</span>(banbox, black_f)</a>
<a class="sourceLine" id="cb117-2" title="2">results_<span class="dv">3</span> &lt;-<span class="st"> </span><span class="kw">summarise</span>(by_race,</a>
<a class="sourceLine" id="cb117-3" title="3">  <span class="dt">avg_delay =</span> <span class="kw">mean</span>(daystoresponse, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</a>
<a class="sourceLine" id="cb117-4" title="4">results_<span class="dv">3</span></a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   black_f avg_delay
##   &lt;fct&gt;       &lt;dbl&gt;
## 1 White        18.7
## 2 Black        20.4</code></pre>
<p><strong>Homework 2:</strong></p>
<p><em>Answer the following questions</em>:
<em>2.1 What is a tibble?</em>
<em>2.2 How is a variable name different from a variable label?"</em>
<em>2.3 What is a labelled vector?</em>
<em>How is the <code>filter()</code> function different from the <code>select()</code> function?</em></p>
<p><strong>Homework 3:</strong></p>
<p><em>For this course unit you need to write a coursework assignment in which you will use data from a social survey to explore relationships between various variables. Specifically, you will be allowed to use. So you will need to pick one of them and then select a topic (of those listed below) to explore with each of these surveys:</em></p>
<p><em>- The 2018 wave of the European Social Survey, which you can access <a href="https://www.europeansocialsurvey.org/download.html?file=ESS9e01_1&amp;y=2018">here</a> and explore <a href="http://nesstar.ess.nsd.uib.no/webview/">here</a>. From this dataset you will be able to explore the following topic: "victimisation in the last 5 years (crmvct)</em></p>
<p><em>- The 2013-2014 Crime Survey for England and Wales (the Teaching Dataset version) which you can access <a href="https://discover.ukdataservice.ac.uk/catalogue/?sn=7911&amp;type=Data%20catalogue">here</a> or explore <a href="http://nesstar.ukdataservice.ac.uk/webview/">here</a>. From this dataset you will need to focus on one of the following topics “fairness of criminal justice system (fairx)”, “confidence in the police in their neighbourhood (confx)”, or “worry about being a victim of crime (worryx)”</em>.</p>
<p><strong>As part of this week homework you need to let us know which survey and which topic you want to focus on for your coursework assignment</strong>.</p>
<p><em>You can explore the datasets and what other variables are available. For your coursework you will need to identify other variables in these surveys that you think may be associated or helpful to understand why people vary in worry of crime, confidence towards the police, etc. At this point you don’t need to identify those other variables, but you may find it useful to explore what’s available in those datasets using NESSTAR (a guide for how to use NESSTAR is available <a href="http://nesstar.com/help/4.0/webview/getting-started/getting-to-know-nesstar-webview.html">here</a> and the existing documentation for those studies</em></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="a-first-lesson-about-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="data-visualisation-with-r.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["book.pdf", "book.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
