<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Data Carpentry | Modelling Criminological Data LAWS20452</title>
  <meta name="description" content="This is the draft for a book on using R for criminologists. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Data Carpentry | Modelling Criminological Data LAWS20452" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the draft for a book on using R for criminologists. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Data Carpentry | Modelling Criminological Data LAWS20452" />
  
  <meta name="twitter:description" content="This is the draft for a book on using R for criminologists. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Juanjo Medina and Reka Solymosi" />


<meta name="date" content="2020-01-31" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="data-visualisation-with-r.html"/>
<link rel="next" href="foundations-of-statistical-inference-confidence-intervals.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Modelling Criminological Data</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html"><i class="fa fa-check"></i><b>1</b> A first lesson about R</a><ul>
<li class="chapter" data-level="1.1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#install-r-rstudio"><i class="fa fa-check"></i><b>1.1</b> Install R &amp; RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#open-up-and-explore-rstudio"><i class="fa fa-check"></i><b>1.2</b> Open up and explore RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#customising-the-rstudio-look"><i class="fa fa-check"></i><b>1.3</b> Customising the RStudio look</a></li>
<li class="chapter" data-level="1.4" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#getting-organised-r-projects"><i class="fa fa-check"></i><b>1.4</b> Getting organised: R Projects</a></li>
<li class="chapter" data-level="1.5" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#talk-to-your-computer"><i class="fa fa-check"></i><b>1.5</b> Talk to your computer</a></li>
<li class="chapter" data-level="1.6" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#more-on-packages"><i class="fa fa-check"></i><b>1.6</b> More on packages</a></li>
<li class="chapter" data-level="1.7" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#using-objects"><i class="fa fa-check"></i><b>1.7</b> Using objects</a></li>
<li class="chapter" data-level="1.8" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#more-on-objects"><i class="fa fa-check"></i><b>1.8</b> More on objects</a></li>
<li class="chapter" data-level="1.9" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#on-comments"><i class="fa fa-check"></i><b>1.9</b> On comments</a></li>
<li class="chapter" data-level="1.10" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#factors"><i class="fa fa-check"></i><b>1.10</b> Factors</a></li>
<li class="chapter" data-level="1.11" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#naming-conventions-for-objects-in-r"><i class="fa fa-check"></i><b>1.11</b> Naming conventions for objects in R</a></li>
<li class="chapter" data-level="1.12" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#dataframes"><i class="fa fa-check"></i><b>1.12</b> Dataframes</a></li>
<li class="chapter" data-level="1.13" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#exploring-data"><i class="fa fa-check"></i><b>1.13</b> Exploring data</a></li>
<li class="chapter" data-level="1.14" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#quitting-rstudio"><i class="fa fa-check"></i><b>1.14</b> Quitting RStudio</a></li>
<li class="chapter" data-level="1.15" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#lab-homework-activities-for-week-1"><i class="fa fa-check"></i><b>1.15</b> Lab homework activities for Week 1</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html"><i class="fa fa-check"></i><b>2</b> Causality in randomised experiments</a><ul>
<li class="chapter" data-level="2.1" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#causality-in-social-sciences"><i class="fa fa-check"></i><b>2.1</b> Causality in social sciences</a></li>
<li class="chapter" data-level="2.2" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#getting-data-thanks-to-reproducibility"><i class="fa fa-check"></i><b>2.2</b> Getting data thanks to reproducibility</a></li>
<li class="chapter" data-level="2.3" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#getting-a-sense-for-your-data"><i class="fa fa-check"></i><b>2.3</b> Getting a sense for your data</a><ul>
<li class="chapter" data-level="2.3.1" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#first-steps"><i class="fa fa-check"></i><b>2.3.1</b> First steps</a></li>
<li class="chapter" data-level="2.3.2" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#on-tibbles-and-labelled-vectors"><i class="fa fa-check"></i><b>2.3.2</b> On tibbles and labelled vectors</a></li>
<li class="chapter" data-level="2.3.3" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#turning-variables-into-factors-and-changing-the-labels"><i class="fa fa-check"></i><b>2.3.3</b> Turning variables into factors and changing the labels</a></li>
<li class="chapter" data-level="2.3.4" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#looking-for-missing-data-and-other-anomalies"><i class="fa fa-check"></i><b>2.3.4</b> Looking for missing data and other anomalies</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#data-wrangling-with-dplyr"><i class="fa fa-check"></i><b>2.4</b> Data wrangling with dplyr</a></li>
<li class="chapter" data-level="2.5" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#using-dplyr-single-verbs"><i class="fa fa-check"></i><b>2.5</b> Using dplyr single verbs</a></li>
<li class="chapter" data-level="2.6" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#using-dplyr-for-grouped-operations"><i class="fa fa-check"></i><b>2.6</b> Using dplyr for grouped operations</a></li>
<li class="chapter" data-level="2.7" data-path="causality-in-randomised-experiments.html"><a href="causality-in-randomised-experiments.html#making-comparisons-with-numerical-outcomes"><i class="fa fa-check"></i><b>2.7</b> Making comparisons with numerical outcomes</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html"><i class="fa fa-check"></i><b>3</b> Data visualisation with R</a><ul>
<li class="chapter" data-level="3.1" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#introduction"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#anatomy-of-a-plot"><i class="fa fa-check"></i><b>3.2</b> Anatomy of a plot</a></li>
<li class="chapter" data-level="3.3" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#what-graph-should-i-use"><i class="fa fa-check"></i><b>3.3</b> What graph should I use?</a></li>
<li class="chapter" data-level="3.4" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#visualising-numerical-variables-histograms"><i class="fa fa-check"></i><b>3.4</b> Visualising numerical variables: Histograms</a></li>
<li class="chapter" data-level="3.5" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#visualising-numerical-variables-density-plots"><i class="fa fa-check"></i><b>3.5</b> Visualising numerical variables: Density plots</a></li>
<li class="chapter" data-level="3.6" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#exploring-relationships-between-two-quantitative-variables-scatterplots"><i class="fa fa-check"></i><b>3.6</b> Exploring relationships between two quantitative variables: scatterplots</a></li>
<li class="chapter" data-level="3.7" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#scatterplots-conditioning-in-a-third-variable"><i class="fa fa-check"></i><b>3.7</b> Scatterplots conditioning in a third variable</a></li>
<li class="chapter" data-level="3.8" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#scatterplot-matrix"><i class="fa fa-check"></i><b>3.8</b> Scatterplot matrix</a></li>
<li class="chapter" data-level="3.9" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#titles-legends-and-themes-in-ggplot2"><i class="fa fa-check"></i><b>3.9</b> Titles, legends, and themes in ggplot2</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-carpentry.html"><a href="data-carpentry.html"><i class="fa fa-check"></i><b>4</b> Data Carpentry</a><ul>
<li class="chapter" data-level="4.1" data-path="data-carpentry.html"><a href="data-carpentry.html#introduction-1"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="data-carpentry.html"><a href="data-carpentry.html#a-template-for-your-assignment"><i class="fa fa-check"></i><b>4.2</b> A template for your assignment</a></li>
<li class="chapter" data-level="4.3" data-path="data-carpentry.html"><a href="data-carpentry.html#thinking-about-your-data-filtering-cases"><i class="fa fa-check"></i><b>4.3</b> Thinking about your data: filtering cases</a></li>
<li class="chapter" data-level="4.4" data-path="data-carpentry.html"><a href="data-carpentry.html#selecting-variables-using-dplyrselect"><i class="fa fa-check"></i><b>4.4</b> Selecting variables: using <code>dplyr::select</code></a></li>
<li class="chapter" data-level="4.5" data-path="data-carpentry.html"><a href="data-carpentry.html#creating-summated-scales"><i class="fa fa-check"></i><b>4.5</b> Creating summated scales</a></li>
<li class="chapter" data-level="4.6" data-path="data-carpentry.html"><a href="data-carpentry.html#collapsing-categories-in-character-variables"><i class="fa fa-check"></i><b>4.6</b> Collapsing categories in character variables</a></li>
<li class="chapter" data-level="4.7" data-path="data-carpentry.html"><a href="data-carpentry.html#working-with-apparently-cryptic-variable-names-and-levels"><i class="fa fa-check"></i><b>4.7</b> Working with apparently cryptic variable names and levels</a></li>
<li class="chapter" data-level="4.8" data-path="data-carpentry.html"><a href="data-carpentry.html#recoding-factors"><i class="fa fa-check"></i><b>4.8</b> Recoding factors</a></li>
<li class="chapter" data-level="4.9" data-path="data-carpentry.html"><a href="data-carpentry.html#understanding-missing-data"><i class="fa fa-check"></i><b>4.9</b> Understanding missing data</a></li>
<li class="chapter" data-level="4.10" data-path="data-carpentry.html"><a href="data-carpentry.html#exploring-dataframes-visually"><i class="fa fa-check"></i><b>4.10</b> Exploring dataframes visually</a></li>
<li class="chapter" data-level="4.11" data-path="data-carpentry.html"><a href="data-carpentry.html#further-resources"><i class="fa fa-check"></i><b>4.11</b> Further resources</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html"><i class="fa fa-check"></i><b>5</b> Foundations of statistical inference: confidence intervals</a><ul>
<li class="chapter" data-level="5.1" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#introduction-2"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#generating-random-data"><i class="fa fa-check"></i><b>5.2</b> Generating random data</a></li>
<li class="chapter" data-level="5.3" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#sampling-distributions-and-sampling-experiments"><i class="fa fa-check"></i><b>5.3</b> Sampling distributions and sampling experiments</a></li>
<li class="chapter" data-level="5.4" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#the-normal-distribution-and-confidence-intervals-with-known-standard-errors"><i class="fa fa-check"></i><b>5.4</b> The normal distribution and confidence intervals with known standard errors</a></li>
<li class="chapter" data-level="5.5" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#asymptotic-confidence-intervals-for-means-and-proportions-using-r"><i class="fa fa-check"></i><b>5.5</b> Asymptotic confidence intervals for means and proportions using R</a></li>
<li class="chapter" data-level="5.6" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#a-brief-intro-to-resampling-and-bootstraping"><i class="fa fa-check"></i><b>5.6</b> A brief intro to resampling and bootstraping</a></li>
<li class="chapter" data-level="5.7" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#what-about-comparisons-sampling-distribution-for-the-difference-of-two-means"><i class="fa fa-check"></i><b>5.7</b> What about comparisons? Sampling distribution for the difference of two means</a></li>
<li class="chapter" data-level="5.8" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#comparing-means-visually-by-using-error-bars-representing-confidence-intervals-inference-by-eye"><i class="fa fa-check"></i><b>5.8</b> Comparing means visually by using error bars representing confidence intervals: inference by eye</a></li>
<li class="chapter" data-level="5.9" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#homework-5.1"><i class="fa fa-check"></i><b>5.9</b> HOMEWORK 5.1</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><i class="fa fa-check"></i><b>6</b> Studying relationships between a categorical and a quantitative variable</a><ul>
<li class="chapter" data-level="6.1" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#the-logic-of-hypothesis-testing"><i class="fa fa-check"></i><b>6.1</b> The logic of hypothesis testing</a></li>
<li class="chapter" data-level="6.2" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#comparing-means-across-two-groups-the-t-test"><i class="fa fa-check"></i><b>6.2</b> Comparing means across two groups (the t test)</a></li>
<li class="chapter" data-level="6.3" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#what-does-a-significant-effect-mean"><i class="fa fa-check"></i><b>6.3</b> What does a significant effect mean?</a></li>
<li class="chapter" data-level="6.4" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#power-analysis"><i class="fa fa-check"></i><b>6.4</b> Power analysis</a></li>
<li class="chapter" data-level="6.5" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#comparing-means-across-several-groups-anova"><i class="fa fa-check"></i><b>6.5</b> Comparing means across several groups (ANOVA)</a><ul>
<li class="chapter" data-level="6.5.1" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#the-problem-with-multiple-comparisons"><i class="fa fa-check"></i><b>6.5.1</b> The problem with multiple comparisons</a></li>
<li class="chapter" data-level="6.5.2" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#anova"><i class="fa fa-check"></i><b>6.5.2</b> ANOVA</a></li>
<li class="chapter" data-level="6.5.3" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#checking-homogeneity-of-variance-and-dealing-with-unequal-spread"><i class="fa fa-check"></i><b>6.5.3</b> Checking homogeneity of variance and dealing with unequal spread</a></li>
<li class="chapter" data-level="6.5.4" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#checking-normality-and-dealing-with-problems"><i class="fa fa-check"></i><b>6.5.4</b> Checking normality and dealing with problems</a></li>
<li class="chapter" data-level="6.5.5" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#robust-anova"><i class="fa fa-check"></i><b>6.5.5</b> Robust ANOVA</a></li>
<li class="chapter" data-level="6.5.6" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#post-hoc-comparisons"><i class="fa fa-check"></i><b>6.5.6</b> Post Hoc Comparisons</a></li>
<li class="chapter" data-level="6.5.7" data-path="studying-relationships-between-a-categorical-and-a-quantitative-variable.html"><a href="studying-relationships-between-a-categorical-and-a-quantitative-variable.html#effect-size-for-anova"><i class="fa fa-check"></i><b>6.5.7</b> Effect size for ANOVA</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="studying-relationships-between-two-factors.html"><a href="studying-relationships-between-two-factors.html"><i class="fa fa-check"></i><b>7</b> Studying relationships between two factors</a><ul>
<li class="chapter" data-level="7.1" data-path="studying-relationships-between-two-factors.html"><a href="studying-relationships-between-two-factors.html#producing-cross-tabulations"><i class="fa fa-check"></i><b>7.1</b> Producing cross tabulations</a></li>
<li class="chapter" data-level="7.2" data-path="studying-relationships-between-two-factors.html"><a href="studying-relationships-between-two-factors.html#expected-frequencies-and-chi-square"><i class="fa fa-check"></i><b>7.2</b> Expected frequencies and Chi-Square</a></li>
<li class="chapter" data-level="7.3" data-path="studying-relationships-between-two-factors.html"><a href="studying-relationships-between-two-factors.html#residuals"><i class="fa fa-check"></i><b>7.3</b> Residuals</a></li>
<li class="chapter" data-level="7.4" data-path="studying-relationships-between-two-factors.html"><a href="studying-relationships-between-two-factors.html#gamma"><i class="fa fa-check"></i><b>7.4</b> Gamma</a></li>
<li class="chapter" data-level="7.5" data-path="studying-relationships-between-two-factors.html"><a href="studying-relationships-between-two-factors.html#odds-and-odd-ratios"><i class="fa fa-check"></i><b>7.5</b> Odds and odd ratios</a></li>
<li class="chapter" data-level="7.6" data-path="studying-relationships-between-two-factors.html"><a href="studying-relationships-between-two-factors.html#homework-7.1"><i class="fa fa-check"></i><b>7.6</b> HOMEWORK 7.1</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html"><i class="fa fa-check"></i><b>8</b> An introduction to regression</a><ul>
<li class="chapter" data-level="8.1" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#introduction-models-in-scientific-research"><i class="fa fa-check"></i><b>8.1</b> Introduction: models in scientific research</a></li>
<li class="chapter" data-level="8.2" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#motivating-regression"><i class="fa fa-check"></i><b>8.2</b> Motivating regression</a></li>
<li class="chapter" data-level="8.3" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#fitting-a-simple-regression-model"><i class="fa fa-check"></i><b>8.3</b> Fitting a simple regression model</a></li>
<li class="chapter" data-level="8.4" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#residuals-revisited-r-squared"><i class="fa fa-check"></i><b>8.4</b> Residuals revisited: R squared</a></li>
<li class="chapter" data-level="8.5" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#inference-with-regression"><i class="fa fa-check"></i><b>8.5</b> Inference with regression</a></li>
<li class="chapter" data-level="8.6" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#fitting-regression-with-categorical-predictors"><i class="fa fa-check"></i><b>8.6</b> Fitting regression with categorical predictors</a></li>
<li class="chapter" data-level="8.7" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#motivating-multiple-regression"><i class="fa fa-check"></i><b>8.7</b> Motivating multiple regression</a></li>
<li class="chapter" data-level="8.8" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#fitting-and-interpreting-a-multiple-regression-model"><i class="fa fa-check"></i><b>8.8</b> Fitting and interpreting a multiple regression model</a></li>
<li class="chapter" data-level="8.9" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#presenting-your-regression-results."><i class="fa fa-check"></i><b>8.9</b> Presenting your regression results.</a></li>
<li class="chapter" data-level="8.10" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#testing-conditional-hypothesis-interactions"><i class="fa fa-check"></i><b>8.10</b> Testing conditional hypothesis: interactions</a></li>
<li class="chapter" data-level="8.11" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#model-building-and-variable-selection"><i class="fa fa-check"></i><b>8.11</b> Model building and variable selection</a></li>
<li class="chapter" data-level="8.12" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#homework"><i class="fa fa-check"></i><b>8.12</b> HOMEWORK</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>9</b> Logistic regression</a><ul>
<li class="chapter" data-level="9.1" data-path="logistic-regression.html"><a href="logistic-regression.html#introduction-3"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="logistic-regression.html"><a href="logistic-regression.html#fitting-logistic-regression"><i class="fa fa-check"></i><b>9.2</b> Fitting logistic regression</a></li>
<li class="chapter" data-level="9.3" data-path="logistic-regression.html"><a href="logistic-regression.html#assessing-model-fit-i-deviance-and-pseudo-r-squared"><i class="fa fa-check"></i><b>9.3</b> Assessing model fit I: deviance and pseudo r squared</a></li>
<li class="chapter" data-level="9.4" data-path="logistic-regression.html"><a href="logistic-regression.html#assessing-model-fit-ii-confusion-matrix-and-roc-curves"><i class="fa fa-check"></i><b>9.4</b> Assessing model fit II: confusion matrix and ROC curves</a></li>
<li class="chapter" data-level="9.5" data-path="logistic-regression.html"><a href="logistic-regression.html#interactions"><i class="fa fa-check"></i><b>9.5</b> Interactions</a></li>
<li class="chapter" data-level="9.6" data-path="logistic-regression.html"><a href="logistic-regression.html#homework-1"><i class="fa fa-check"></i><b>9.6</b> HOMEWORK:</a></li>
<li class="chapter" data-level="9.7" data-path="logistic-regression.html"><a href="logistic-regression.html#further-resources-1"><i class="fa fa-check"></i><b>9.7</b> Further resources</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Modelling Criminological Data LAWS20452</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-carpentry" class="section level1">
<h1><span class="header-section-number">Chapter 4</span> Data Carpentry</h1>
<div id="introduction-1" class="section level2">
<h2><span class="header-section-number">4.1</span> Introduction</h2>
<p>We have already introduce the typical workflow of data analysis:</p>
<p><img src="imgs/data-science-explore.png" />
In this figure produced by Hadley Wickham you can see the first stage of data analysis involve importing your data, getting it into a <a href="http://vita.had.co.nz/papers/tidy-data.pdf">tidy format</a>, and then doing some transformations so that you get the data in good shape for analysis. There is a famous and possibly false statistic that says that 80% of an analyst time is often devoted to this kind of operations. Although the statistic is likely made up, the truth is that the experience of many analysts resonates with it. So, you should not underestimate data carpentry or data wrangling (as these processes are often called) as a part of your analysis.</p>
<p>For various decades, social scientists of a quantitative persuasion worked primarily with survey data (for an excelent history of how this come to be you can read <a href="https://global.oup.com/academic/product/identities-and-social-change-in-britain-since-1940-9780199587650?cc=gb&amp;lang=en&amp;#">this book</a>), which came in rather tidy formats, but often required some transformations. Today we are more likely to rely on “big” and other new forms of data (from the web, administrative sources, or a variety of sensors) that may require more significant processing before we can do any analysis with it. Think, for example, of data from online vendors of drugs available in the Dark Net. Some people talk of the advent of a new <a href="http://science.sciencemag.org/content/323/5915/721/tab-pdf">computational social science</a> around these new methods. This kind of data, indeed, opens avenues for research we could only dream of in the past as argued by <a href="https://www.sciencedirect.com/science/article/pii/S0955395919300313?via%3Dihub">some of our colleagues</a>. But getting this kind of data requires the development of new skills (e.g, web scrapping) and generally requires more processing before they are tidy and ready for analysis.</p>
<p>R is particularly well suited for this new world. In this module we only work with survey data, which tends to be tidier and easier to work with in the context of an introductory course unit. But even when working with this kind of data you often have to think hard about required tidying and transformations before you can start your analysis.</p>
<p>In this module we expect you to download a survey dataset for analysis. These datasets are already rather tidy and have been professionally cleaned and prepared for analytical consumption. But you may still have to select cases and variables that are appropriate for your own analysis. Also, you likely will need to generate new variables or change existing ones for various reasons. It’s a rare data set in which every variable you need is measured directly. Examples of things you may need to do include:</p>
<ul>
<li>Combine various variables into a new one (eg., computing a rate)</li>
<li>Reduce the number of levels in a categorical variable</li>
<li>Format the variable to assign it to a more appropriate class if this is called for (e.g., character into factor). You will need to format date variables as dates, numerical variables as numbers, etc.).</li>
<li>Recode values identifying missing cases as NA.</li>
<li>Labelling all variables and categorical values so you don’t have to keep looking them up.</li>
<li>Change the labels associated with the levels of a categorical variable.</li>
</ul>
</div>
<div id="a-template-for-your-assignment" class="section level2">
<h2><span class="header-section-number">4.2</span> A template for your assignment</h2>
<p>For this practical we are going to proceed as if we had an assignment similar to your final assignment for this module. Only that we will use different data, specifically data from a <em>Eurobarometer</em>. Eurobarometers are opinion polls conducted regularly on behalf of the European Commission since 1973. Some of them ask the same questions over time to evaluate changes in European’s views in a variety of subjects (standard Eurobarometers). Others are focused on special topics and are conducted less regularly (special Eurobarometers). They are a useful source of datasets that you could use, for exampple, for your undergraduate dissertation.</p>
<p>The data from these surveys is accessible through the data catalogue of GESIS, a data warehouse at the <em>Leibniz Institute for the Social Sciences</em> in Germany. For downloading data from GESIS you have to register with them (following the registration link) <a href="https://dbk.gesis.org/dbksearch/register.asp">here</a>. Once you activate your registration you should be able to access the data at GESIS.</p>
<p><img src="imgs/register.PNG" /></p>
<p>GESIS has a section of their website devoted to the Eurobarometer survey. You can access that section <a href="https://www.gesis.org/eurobarometer-data-service/home/">here</a>. You could navigate this webpage to find the data we will be using for this tutorial, but to save time I will provide you a direct link to it. We will be using the special Eurobarometer 85.3 form 2016. This survey among other things asked Europeans about their views on gender violence.</p>
<p><img src="imgs/eb.PNG" /></p>
<p>You can access the data for this eurobarometer <a href="https://dbk.gesis.org/dbksearch/sdesc2.asp?no=6695&amp;db=e&amp;doi=10.4232/1.13169">here</a>.</p>
<p><img src="imgs/gesis.PNG" /></p>
<p>You will see here that there are links to the files with the data in SPSS and STATA format. You can also see a tab where you could obtain the questionnaire for the survey. Once you are registered download the STATA version of the file and also an English version of the questionnaire. Make sure you place the file in your working directory. Once you do this you should be able to use the code we are using in this session.</p>
<p>First, we will load the data into our session. Since the data is in STATA format we will need to read the data into R using the <code>haven</code> package. Specifically, we will use the <code>read_dta</code> function for importing STATA data into R. As an argument we need to write the name of the file with the data (and if it is not in your working directory, the appropriate path file).</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb196-1" title="1"><span class="kw">library</span>(haven)</a>
<a class="sourceLine" id="cb196-2" title="2">eb85_<span class="dv">3</span> &lt;-<span class="st"> </span><span class="kw">read_dta</span>(<span class="st">&quot;ZA6695_v1-1-0.dta&quot;</span>)</a>
<a class="sourceLine" id="cb196-3" title="3"><span class="kw">dim</span>(eb85_<span class="dv">3</span>)</a></code></pre></div>
<pre><code>## [1] 27818   483</code></pre>
<p>We can see there are over 27000 cases (survey participants) and 483 variables.</p>
</div>
<div id="thinking-about-your-data-filtering-cases" class="section level2">
<h2><span class="header-section-number">4.3</span> Thinking about your data: filtering cases</h2>
<p>For the final coursework assignment, you will need to download other datasets but the process will be similar in that once you have the datasets you will need to think about what cases and what variables you want to work with. Imagine that we had to write our final assignment using this dataset and that we had to write a report about attitudes to sexual violence.</p>
<p>First, we would need to think if we wanted to use all cases in the data or only a subset of the cases. For example, when using something like the Eurobarometer we would need to consider if we are interested in exploring the substantive topic across Europe or only for some countries. Or alternatively you may want to focus your analysis only on men attitudes to sexual violence. In a situation like this you would need to filter cases. This decision needs to be guided by your theoretical interests and your driving research question.</p>
<p>So, for example, if we only wanted to work with the UK sample we would need to figure out if there is a variable that identifies the country in the dataset. In the questionnaire you can see indeed that there is such a variable:</p>
<p><img src="imgs/question1.PNG" /></p>
<p>What we do not know is how this variable is named in the dataset. For this we need to look at the <em>codebook</em>. In this case, we can look at the interactive facility provided for GESIS for online data analysis, which provides an interactive online codebook for this dataset. You can access this facility in the link highlighted in the image below:</p>
<p><img src="imgs/linktoonline.PNG" /></p>
<p>You can access similar applications for the two datasets that you need to use for the final coursework assignment. If you will use the ESS you can use an online facility <a href="http://nesstar.ess.nsd.uib.no/webview/">here</a> and if you are using the CSEW you can access a similar tool <a href="http://nesstar.ukdataservice.ac.uk/webview/">here</a>.</p>
<p>Let’s explore the online facility for the Eurobarometer. If we expand the menus in the left hand side by clicking in variable description, and then in standard nation id variables, you will see there is a variable that provides a “country code”. This must be it. click on it and then you will see in the right hand side some information about this variable. You see the name of this variable (as it will appear in the dataset) <em>isocntry</em> and we can see this variable uses <a href="https://en.wikipedia.org/wiki/ISO_3166">ISO 3166</a> codes to designate the country. This is an international standard set of abbreviations for country names. For the UK these codes are “GB-GBN” and “GB-NIR” (for Northern Ireland).</p>
<p><img src="imgs/country.PNG" /></p>
<p>Now that we have this information we can run the code to select only the cases that have these values in the dataset. For doing something like that we would use the <code>dplyr::filter</code> function. We used the <code>filter</code> function in week 2. You can read more about it in the <code>dplyr</code> vignette.</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb198-1" title="1"><span class="kw">library</span>(dplyr)</a>
<a class="sourceLine" id="cb198-2" title="2"><span class="co">#First, let&#39;s see what type of vector isocntry is</span></a>
<a class="sourceLine" id="cb198-3" title="3"><span class="kw">class</span>(eb85_<span class="dv">3</span><span class="op">$</span>isocntry)</a></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb200-1" title="1">uk_eb85_<span class="dv">3</span> &lt;-<span class="st"> </span><span class="kw">filter</span>(eb85_<span class="dv">3</span>, isocntry <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;GB-GBN&quot;</span>, <span class="st">&quot;GB-NIR&quot;</span>))</a></code></pre></div>
<p>The variable <em>isocntry</em> is a character vector with codes for the different participating countries. Here we want to select all the cases in the survey that have either of two values in this vector (GB-GBN or GB-NIR). Since these values are text we need to use quotes to wrap them up. Because we are selecting more than one value we cannot simply say <code>isocntry == "GB-BGN"</code>. We also need the cases from Northern Ireland. So, we use a particular operator introduced by <code>dplyr</code> called the piping operator (<code>%in%</code>). The piping operator is essentially saying to R <em>“and then”</em>. Basically, here we are creating a vector with the values we want <em>and then</em> asking R to look at those values within tne list (containing the right labels) in the the <em>isocntry</em> vector so that we can filter everything else out.</p>
<p>If you run this code you will end up with a new object called <code>uk_eb85_3</code> that only has 1306 observations. We have now a dataset that only has the British participants.</p>
</div>
<div id="selecting-variables-using-dplyrselect" class="section level2">
<h2><span class="header-section-number">4.4</span> Selecting variables: using <code>dplyr::select</code></h2>
<p>Perhaps for your coursework you define your essay question in such a way that you do not need to do any a priory filtering. Perhaps, for the sake of this example, we decide to do an analysis that focuses on looking at attitudes toward sexual violence for all of Europe and for all participants. Yet, you won’t be using 483 variables for certain. Among other reasons because our guidelines for the essay suggest you use fewer variables. But more generally because typically your theoretical model will tell you that some things matter more than others. The first thing you need to do is to think about what variables you are going to use. This involves first thinking about what variables are available in the dataset that measure your outcome of interest but then also consider what your theory of attitudes to gender violence say (this generally will include things that are not measured in the survey, such is life!).</p>
<p>The thing you are interested in explaining or better understanding is attitudes regarding sexual violence. So, before anything else you would need to spend some time thinking about how this survey measures these attitudes. You would need to screen the questionnaire and the codebook to identify these variables and their names in the dataset. Have a look at the questionnaire. The questions about gender violence start at the bottom of page 7. Which of these questions are questions about attitudes towards sexual violence?</p>
<p><strong>Homework 4.1:</strong>
<em>Identify the name of all the variables that pertain to attitudes toward sexual violence.</em></p>
<p>Once you have all of this you would need to think about which of these survey questions and items make more sense for your research question. This is something where you will need to use your common sense but also your understanding of the literature in the topic. Criminologists and survey researchers spend a lot of time thinking about what is the best way of asking questions about topics or concepts of interest. They often debate and write about this. In data analysis measurement is key and is the process of systematically assigning numbers to objects and their properties, to facilitate the use of mathematics in studying and describing objects and their relationships. So, as part of your essay, you will need to consider what do researchers consider are good questions to measure, to tap into, the abstract concepts you are studying.</p>
<p>There are many items in this survey that relate to this topic (and you need to identify as part of homework 4.1), but for purposes of continuing our illustration we are going to focus on the answers to question <em>QB10</em>. This question asks respondents to identify in what circumstances may be justified to have sexual intercourse without consent. The participants are read a list of items (e.g., “flirting before hand”) and they can select various of them if so they wish.</p>
<p><img src="imgs/qb10.PNG" /></p>
<p>Ok, so we have now selected our variable. Say that we have done so on the basis of our understanding of the literature. Next we need to identify these variables in the dataset. What name is associated with this variable? Let’s look at the online interactive facility.</p>
<p><img src="imgs/qb10codes.PNG" /></p>
<p>Damn! We have one question but several variables! This is common when the question in the survey allows for multiple responses. Typically when this is read into a dataset, survey researchers create a variable for each of the possible multiple responses. If the respondent identified one of those potential responses they will be assigned a “yes” or a “1” for that column. If they did not they will be assigned a “no” or a “0”. Let’s see how this was done in this case:</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb201-1" title="1"><span class="kw">class</span>(eb85_<span class="dv">3</span><span class="op">$</span>qb10_<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] &quot;haven_labelled&quot;</code></pre>
<p>This is a vector labelled by haven. We could see what labels were used using the <code>attributes</code> function.</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb203-1" title="1"><span class="kw">attributes</span>(eb85_<span class="dv">3</span><span class="op">$</span>qb10_<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## $label
## [1] &quot;INTERCOURSE W/O CONSENT APPROPRIATE WHEN: WEARING SEXY CLOTHES&quot;
## 
## $format.stata
## [1] &quot;%8.0g&quot;
## 
## $class
## [1] &quot;haven_labelled&quot;
## 
## $labels
## Not mentioned     Mentioned 
##             0             1</code></pre>
<p>We can see here that the value 1 corresponds to cases where this circumstance was mentioned. Let’s see how many people considered this a valid circumstance to have sex without consent.</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb205-1" title="1"><span class="kw">table</span>(eb85_<span class="dv">3</span><span class="op">$</span>qb10_<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## 
##     0     1 
## 24787  3031</code></pre>
<p>Fortunately, only a minority of respondents.</p>
<p>Apart from thinking about the variables we will use to measure our outcome of interest for the coursework assignment you will need to select some variables that you think may be associated with this outcome. In the essay you will need to select a wider set. Here we will only do a few. Again, this is something that needs to be informed by the literature (what variables does the literature considers important) and your own interest.</p>
<p>For the sake of illustration, let’s say we are going to look at gender, political background of the respondent, country of origin, age, occupation of the respondents, and type of community they live in. Most of these are demographic variables (not always the more fun or theoretically interesting), but that’s all we have in this eurobarometer and so they will have to do.</p>
<p>The same way you try to identify the names of the variables for your outcome variable, you would need to do this for the variables you use to “explain” your outcome. Once you have done your variable selection you can subset your data to only include these.</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb207-1" title="1">df &lt;-<span class="st"> </span><span class="kw">select</span>(eb85_<span class="dv">3</span>, qb10_<span class="dv">1</span>, qb10_<span class="dv">2</span>, qb10_<span class="dv">3</span>, qb10_<span class="dv">4</span>,</a>
<a class="sourceLine" id="cb207-2" title="2">             qb10_<span class="dv">5</span>, qb10_<span class="dv">6</span>, qb10_<span class="dv">7</span>, qb10_<span class="dv">8</span>, qb10_<span class="dv">9</span>,</a>
<a class="sourceLine" id="cb207-3" title="3">             qb10_<span class="dv">10</span>, qb10_<span class="dv">11</span>, qb10_<span class="dv">12</span>, d10, d11,</a>
<a class="sourceLine" id="cb207-4" title="4">             isocntry, d1, d25, d15a, uniqid)</a></code></pre></div>
<p>Ta-da! We now have a new object called <em>df</em> with only the variables we will be working with. In this format, it is easier to visualise the data. Notice we have also added a variable called <code>uniqid</code>. With many datasets like this you will have a unique id value that allows you to identify individuals. This id may be handy later on, so we will preserve it in our object.</p>
<p>If you <code>View</code> this object <em>df</em> you will notice that the selected variables appear in the order you selected them. If you wanted a different arrangement, for example you may have preferred to have <em>uniqid</em> as your first column, you could have modified the code like so:</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb208-1" title="1">df &lt;-<span class="st"> </span><span class="kw">select</span>(eb85_<span class="dv">3</span>, uniqid, qb10_<span class="dv">1</span>, qb10_<span class="dv">2</span>, qb10_<span class="dv">3</span>, qb10_<span class="dv">4</span>,</a>
<a class="sourceLine" id="cb208-2" title="2">             qb10_<span class="dv">5</span>, qb10_<span class="dv">6</span>, qb10_<span class="dv">7</span>, qb10_<span class="dv">8</span>, qb10_<span class="dv">9</span>,</a>
<a class="sourceLine" id="cb208-3" title="3">             qb10_<span class="dv">10</span>, qb10_<span class="dv">11</span>, qb10_<span class="dv">12</span>, d10, d11,</a>
<a class="sourceLine" id="cb208-4" title="4">             isocntry, d1, d25, d15a)</a></code></pre></div>
<p>Or if you just want to reorder one or few columns (for example you want to also move d1, d25 and d15 a to the front), you could use <code>everything()</code> afterwards to save some typing, as below:</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb209-1" title="1">df &lt;-<span class="st"> </span><span class="kw">select</span>(df, uniqid, d1, d25, d15a, <span class="kw">everything</span>())</a></code></pre></div>
<p>If you want to add a lot of columns, it can save you some typing to have a good look at your data and see whether you can’t get to your selection by using chunks. Since <em>qb10_1</em> and the others are one after the other in the dataset we can use the <code>start.col:end.col</code> syntax like below:</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb210-1" title="1">df &lt;-<span class="st"> </span><span class="kw">select</span>(eb85_<span class="dv">3</span>, uniqid, qb10_<span class="dv">1</span><span class="op">:</span>qb10_<span class="dv">12</span>, d10, d11,</a>
<a class="sourceLine" id="cb210-2" title="2">             isocntry, d1, d25, d15a)</a></code></pre></div>
<p>If you have a lot of columns with a similar structure you can use partial matching by adding <code>starts_with()</code>, <code>ends_with()</code> or <code>contains()</code> in your select statement. So, for example, an alternative to the syntax above we could use the following:</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb211-1" title="1">df &lt;-<span class="st"> </span><span class="kw">select</span>(eb85_<span class="dv">3</span>, uniqid, <span class="kw">starts_with</span>(<span class="st">&quot;qb10&quot;</span>), d10, d11,</a>
<a class="sourceLine" id="cb211-2" title="2">             isocntry, d1, d25, d15a)</a></code></pre></div>
<p>Notice how the text we pass as an argument goes between double quotes.</p>
<p>An alternative is to deselect columns by adding a minus sign in front of the column name. You can also deselect chunks of columns. <strong>Don’t execute the code below for this practical</strong>, but if you wanted, for example to get rid of <em>uniqid</em> you could do the following:</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb212-1" title="1">df &lt;-<span class="st"> </span><span class="kw">select</span>(df, <span class="op">-</span>uniqid)</a></code></pre></div>
<p>Yes, a lot of these tips are about saving you some typing. Being lazy (productive, efficient) is fine. You can find more tips like this and useful ideas if you want to rename your columns or variables in <a href="https://suzan.rbind.io/2018/01/dplyr-tutorial-1/">this tutorial</a>.</p>
</div>
<div id="creating-summated-scales" class="section level2">
<h2><span class="header-section-number">4.5</span> Creating summated scales</h2>
<p>Now comes the next part. What are we going to do with these variables? How are we going to use them? Here you need to do some thinking using your common sense and also considering how other researchers may have used this question about attitudes to sexual violence. There’s always many possibilities.</p>
<p>We could, for example, consider that we are going to split the sample in two: those that consider any of these circumstances valid and those that didn’t. We would then end up with a binary indicator that we could use as our outcome variable in our analysis.</p>
<p>The thing is that doing that implies loosing information. We may think that someone that consider many circumstances as valid is not the same than the person that only considers one as valid. Yet, creating a global binary indicator would treat these two individuals in the same way.</p>
<p>Another alternative could be to see how many of these circumstances are considered valid excuses for each individual and to produce a sum then for every respondent. Since there are 9 “excuses” we could have a sum from 0 to 9. This is a very rough <strong>summated scale</strong>. You can read more about the proper development of summated scales <a href="https://pdfs.semanticscholar.org/aa84/dc485a07b920a957e9ef295e8dced8fa025c.pdf">here</a>.</p>
<p>Let’s do this. We are going to create a new variable that add up the responses to <em>qb10_1</em> all the way to <em>qb10_9</em>. For this we use the <code>mutate</code> function from the <code>dplyr</code> package.</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb213-1" title="1">df &lt;-<span class="st"> </span><span class="kw">mutate</span>(df, </a>
<a class="sourceLine" id="cb213-2" title="2">       <span class="dt">at_sexviol =</span> qb10_<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>qb10_<span class="dv">2</span> <span class="op">+</span><span class="st"> </span>qb10_<span class="dv">3</span> <span class="op">+</span><span class="st"> </span>qb10_<span class="dv">4</span> <span class="op">+</span></a>
<a class="sourceLine" id="cb213-3" title="3"><span class="st">         </span>qb10_<span class="dv">5</span> <span class="op">+</span><span class="st"> </span>qb10_<span class="dv">6</span> <span class="op">+</span><span class="st"> </span>qb10_<span class="dv">7</span> <span class="op">+</span><span class="st"> </span>qb10_<span class="dv">8</span> <span class="op">+</span><span class="st"> </span>qb10_<span class="dv">9</span>)</a>
<a class="sourceLine" id="cb213-4" title="4"><span class="kw">table</span>(df<span class="op">$</span>at_sexviol)</a></code></pre></div>
<pre><code>## 
##     0     1     2     3     4     5     6     7     8     9 
## 19681  2529  2117  1643   841   416   255   155    57   124</code></pre>
<p>We have a skewed distribution. Most people in the survey consider that none of the identified circumstances are valid excuses for having sexual intercourse without consent. On the other hand, only a minority of individuals (124) consider that all of these 9 circumstances are valid excuses for having sex without consent. A high score in this count variable is telling you the participant is more likely to accept a number of circumstances in which sexual intercourse without consent is acceptable. You may read more about count data of this kind <a href="https://en.wikipedia.org/wiki/Count_data">here</a>.</p>
<p>Hold on for a second, though. There is a variable <code>qb10_10</code> that specifies people that answered “none of these” circumstances. In theory the number of people with a “1” in that variable (that is, selected this item) should equal 19681 (the number of zeros in our new variable). Let’s check this out:</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb215-1" title="1"><span class="kw">table</span>(df<span class="op">$</span>qb10_<span class="dv">10</span>)</a></code></pre></div>
<pre><code>## 
##     0     1 
##  9400 18418</code></pre>
<p>Oops! Something doesn’t add up! Only 18418 people said that none of these circumstances were valid. So why when we add all the other items we end up with 19681 rather than 18418? Notice that there is also a qb10_11 and a qb10_12. These two items identify the people that refused to answer this question and those which did not know how to answer it.</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb217-1" title="1"><span class="kw">table</span>(df<span class="op">$</span>qb10_<span class="dv">11</span>)</a></code></pre></div>
<pre><code>## 
##     0     1 
## 27563   255</code></pre>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb219-1" title="1"><span class="kw">table</span>(df<span class="op">$</span>qb10_<span class="dv">12</span>)</a></code></pre></div>
<pre><code>## 
##     0     1 
## 26810  1008</code></pre>
<p>There are 255 people that refused to answer and 1008 that did not know how to answer. If you add 1008, 255, and 18418 you get 19681. So our new variable is actually computing as zeroes people that did not know how to answer this question or refused to answer it. We do not want that. We do not know what these people think, so it would be wrong to assume that they consider that none of these circumstances are valid excuses for sexual intercourse without consent.</p>
<p>There are many ways to deal with this. He could simply filter out cases where we have values of 1 in these two variables (since we don’t know their answers we could as well get rid of them). But We could also recode the variable to define this values as what they are NA (missing data, cases for which we have no valid information).</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb221-1" title="1">df<span class="op">$</span>at_sexviol[df<span class="op">$</span>qb10_<span class="dv">11</span> <span class="op">==</span><span class="st"> </span><span class="dv">1</span> <span class="op">|</span><span class="st"> </span>df<span class="op">$</span>qb10_<span class="dv">12</span> <span class="op">==</span><span class="st"> </span><span class="dv">1</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></a>
<a class="sourceLine" id="cb221-2" title="2"><span class="kw">table</span>(df<span class="op">$</span>at_sexviol)</a></code></pre></div>
<pre><code>## 
##     0     1     2     3     4     5     6     7     8     9 
## 18418  2529  2117  1643   841   416   255   155    57   124</code></pre>
<p>Pay attention to the code above. When we want to recode based in a condition we use something like that. What we are saying with that code is that we are going to assign as “NA” (missing data) the cases for which the condition between the square brackets are met. Those conditions are as defined, when the participants answered don’t know <em>or</em> (the logical operator for “or” is “|”) refused to answer the question (that is when <em>qb10_11</em> or <em>qb10_12</em> equals 1). You can see other scenarios for recoding using this kind of syntax in the resources we link below. You can see other logical operators used in R <a href="https://www.datamentor.io/r-programming/operator/">here</a>.</p>
<p>Notice that once we do the recoding and rerun the frequency distribution you will see we achieved what we wanted. Now all those missing cases are not counted as zero.</p>
<p>Summated scales like the one we created here are quick and not the most kosher way of combining several questions into a single measure. In research methods you probably learnt that we often work with theoretical constructs that we do not observe directly (e.g., self control, anomie, collective efficacy, etc.). We often call these <strong>latent variables</strong>. In order to study these constructs we create measures or scales that are based in <strong>observed variables</strong> (those we actually include and ask in the survey). <a href="https://www.ismanet.org/doctoryourspirit/pdfs/Beck-Depression-Inventory-BDI.pdf">This</a> is a famous measure of <em>depression</em> often used in research. As you can see we have different questions (our oberved variables) that we think are related to our latent or not observed (directly) variable (<em>depression</em>). You can also see there are several items or questions all of which we researchers think are linked to depression in this scale. If you provide positive answers to many of these questions we may think that you have this unobserved thing we call <em>depression</em>.</p>
<p>When measuring latent variables it is a good idea to have multiple items that all capture aspects of the unobserved variable we are really interested in measuring. There is a whole field of statistics that focuses in how to analise if your observed variables are good indicators of your unobserved variable (<strong>psychometry</strong> is how we call this field in psychology) and also that focuses on how to best combine the answers to our observed variables in a single score (<strong>latent variable modelling</strong>). Some of the scores in the Crime Survey for England and Wales that you may use for your essay have been created with this more advanced methods (some of the measures on confidence in the police, for example). Summated scales are not really the best way to do this. But these are more advanced topics that are covered in upper level undergraduate or postgraduate courses. So for now, we will use summated scales as a convenient if imperfect way of aggregating observed variables.</p>
</div>
<div id="collapsing-categories-in-character-variables" class="section level2">
<h2><span class="header-section-number">4.6</span> Collapsing categories in character variables</h2>
<p>One of the variables we selected is the country in which the participant lives. Let’s have a look at this variable.</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb223-1" title="1"><span class="kw">table</span>(df<span class="op">$</span>isocntry)</a></code></pre></div>
<pre><code>## 
##     AT     BE     BG     CY     CZ   DE-E   DE-W     DK     EE     ES     FI 
##   1016   1029   1001    501   1060    533   1052   1010   1001   1008   1042 
##     FR GB-GBN GB-NIR     GR     HR     HU     IE     IT     LT     LU     LV 
##   1009   1006    300   1000   1026   1046   1002   1013   1004    508   1010 
##     MT     NL     PL     PT     RO     SE     SI     SK 
##    500   1003   1002   1000   1007   1109   1012   1008</code></pre>
<p>There are 30 countries in the sample. You may consider that for the purposes of your analysis maybe that is too much. For the sake of this tutorial, let’s say that maybe you are not really interested in national differences but in regional differences across different parts of Europe. Say you may want to explore whether these attitudes are different across Western/Central Europe, Scandinavian countries, Mediterranean countries, and Eastern Europe. You do not have a variable with these categories but since you have a variable that gives you the nations you could create such a variable. How would you do that?</p>
<p>First, you need to consider what the new categories are going to be and how you are going to distribute the countries in your sample across those categories. You may do that in a piece of paper. Then you would need to write the code to have a new variable with this information.</p>
<p>We are going to group the countries in 4 regions: Western (AT, BE, CZ, DE-E, DE-W, FR, GB-GBN, GB-NIR, IE, LU, NL), Eastern (BG, EE, HU, LT, LV, PL, RO, SK), Southern (CY, ES, GR, HR, IT, MT, PT, SI), and Northern Europe (DK, FI, SE).</p>
<p>Then you need to figure out what kind of variable we are dealing with here:</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb225-1" title="1"><span class="kw">class</span>(df<span class="op">$</span>isocntry)</a></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p>Ok, this is a categorical unordered variable, we know that. But this kind of variables could be encoded into R as either <em>character</em> vectors, <em>factor</em> variables, or as we have seen as well as <em>haven_labelled</em>. How you recode a variable is contingent in how it is encoded. Here we are going to show you how you would do the recoding with a <em>character</em> variable such as <em>isocntry</em> into another character variable we will call <em>region</em>. We will see later examples for how to recode <em>factors</em>.</p>
<p><strong>Homework 4.2:</strong>
<em>Explain in your own words the difference between a character vector, a factor variable, and a haven_labelled vector</em></p>
<p>We will have a variable with four new categories (Western, Southern, Eastern, and Northern) whenever the right conditions are met. See the code below:</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb227-1" title="1">df<span class="op">$</span>region[df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;AT&quot;</span> <span class="op">|</span><span class="st"> </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;BE&quot;</span> <span class="op">|</span><span class="st"> </span></a>
<a class="sourceLine" id="cb227-2" title="2"><span class="st">            </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;CZ&quot;</span> <span class="op">|</span><span class="st"> </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;DE-E&quot;</span> <span class="op">|</span></a>
<a class="sourceLine" id="cb227-3" title="3"><span class="st">            </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;DE-W&quot;</span> <span class="op">|</span><span class="st"> </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;FR&quot;</span> <span class="op">|</span></a>
<a class="sourceLine" id="cb227-4" title="4"><span class="st">            </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;GB-GBN&quot;</span> <span class="op">|</span><span class="st"> </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;GB-NIR&quot;</span> <span class="op">|</span></a>
<a class="sourceLine" id="cb227-5" title="5"><span class="st">            </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;IE&quot;</span> <span class="op">|</span><span class="st"> </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;LU&quot;</span> <span class="op">|</span></a>
<a class="sourceLine" id="cb227-6" title="6"><span class="st">            </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;NL&quot;</span>] &lt;-<span class="st"> &quot;Western&quot;</span></a>
<a class="sourceLine" id="cb227-7" title="7">df<span class="op">$</span>region[df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;BG&quot;</span> <span class="op">|</span><span class="st"> </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;EE&quot;</span> <span class="op">|</span></a>
<a class="sourceLine" id="cb227-8" title="8"><span class="st">            </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;HU&quot;</span> <span class="op">|</span><span class="st"> </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;LT&quot;</span> <span class="op">|</span></a>
<a class="sourceLine" id="cb227-9" title="9"><span class="st">            </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;LV&quot;</span> <span class="op">|</span><span class="st"> </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;PL&quot;</span> <span class="op">|</span></a>
<a class="sourceLine" id="cb227-10" title="10"><span class="st">            </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;RO&quot;</span> <span class="op">|</span><span class="st"> </span></a>
<a class="sourceLine" id="cb227-11" title="11"><span class="st">            </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;SK&quot;</span>] &lt;-<span class="st"> &quot;Eastern&quot;</span></a>
<a class="sourceLine" id="cb227-12" title="12">df<span class="op">$</span>region[df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;DK&quot;</span> <span class="op">|</span><span class="st"> </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st">&quot;FI&quot;</span> <span class="op">|</span></a>
<a class="sourceLine" id="cb227-13" title="13"><span class="st">            </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;SE&quot;</span>] &lt;-<span class="st"> &quot;Northern&quot;</span></a>
<a class="sourceLine" id="cb227-14" title="14">df<span class="op">$</span>region[df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;CY&quot;</span> <span class="op">|</span><span class="st"> </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;ES&quot;</span> <span class="op">|</span></a>
<a class="sourceLine" id="cb227-15" title="15"><span class="st">            </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;GR&quot;</span> <span class="op">|</span><span class="st"> </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st">&quot;HR&quot;</span> <span class="op">|</span></a>
<a class="sourceLine" id="cb227-16" title="16"><span class="st">            </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;IT&quot;</span> <span class="op">|</span><span class="st"> </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st">&quot;MT&quot;</span> <span class="op">|</span></a>
<a class="sourceLine" id="cb227-17" title="17"><span class="st">            </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st"> &quot;PT&quot;</span> <span class="op">|</span><span class="st"> </span></a>
<a class="sourceLine" id="cb227-18" title="18"><span class="st">            </span>df<span class="op">$</span>isocntry <span class="op">==</span><span class="st">&quot;SI&quot;</span>] &lt;-<span class="st"> &quot;Southern&quot;</span></a>
<a class="sourceLine" id="cb227-19" title="19"></a>
<a class="sourceLine" id="cb227-20" title="20"><span class="kw">table</span>(df<span class="op">$</span>region)</a></code></pre></div>
<pre><code>## 
##  Eastern Northern Southern  Western 
##     8079     3161     7060     9518</code></pre>
<p>What we are doing above is initialising a new variable in the <em>df</em> object that we are calling <em>region</em>. We are then assigning to each of the four categories in this character vector those participants in the survey that have the corresponding values in the <em>isocntry</em> variable as defined for each category within the square brackets. So for example if Austria is the value in <em>isocntry</em> we are telling R we want this person to be assigned the value of “Western” in the <em>region</em> variable. And so on. You can see the list of ISO country codes <a href="https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes">here</a>.</p>
<p>Once you have created the variable you could start exploring if there is any association with our outcome variable. For example, using <strong>mosaic plots</strong> from the <code>vcd</code> package (if you don’t have it installed the code won’t run).</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb229-1" title="1"><span class="kw">library</span>(vcd)</a></code></pre></div>
<pre><code>## Loading required package: grid</code></pre>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb231-1" title="1"><span class="kw">mosaic</span>(<span class="op">~</span>region <span class="op">+</span><span class="st"> </span>at_sexviol, <span class="dt">data =</span> df)</a></code></pre></div>
<p><img src="04-carpentry_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>In a mosaic plot like this the height of the region levels indicate how big that group is. You can see there are many more observations in our sample that come from Western countries than from Northern countries. Here what we are interested is the length. We see that Northern countries have proportionally more people in the zero category than any other group. On the other hand, Eastern countries have the fewer zeros (so looking as if attitudes more permissive towards sexual violence are more common there, even if still a minority). We will come back to this kind of plots later on this semester.</p>
</div>
<div id="working-with-apparently-cryptic-variable-names-and-levels" class="section level2">
<h2><span class="header-section-number">4.7</span> Working with apparently cryptic variable names and levels</h2>
<p>Let’s look at the variable <em>d10</em> in our dataset:</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb232-1" title="1"><span class="kw">table</span>(df<span class="op">$</span>d10)</a></code></pre></div>
<pre><code>## 
##     1     2 
## 12230 15588</code></pre>
<p>What is this? Unclear, isn’t it? If you look at the questionnaire you will see that this variable measures gender, that values of 1 correspond to men and that values of 2 corresponds to woman. But this is far from straightforward just by looking a the printed table or the name of the variable.</p>
<p>To start with we may want to change the name of the variable. One way to do this is the following:</p>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb234-1" title="1"><span class="kw">colnames</span>(data)[<span class="kw">colnames</span>(data)<span class="op">==</span><span class="st">&quot;old_name&quot;</span>] &lt;-<span class="st"> &quot;new_name&quot;</span></a></code></pre></div>
<p>Of course, we need to change the names for valid ones in our case. So adapting that code we would write as follows:</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb235-1" title="1"><span class="kw">colnames</span>(df)[<span class="kw">colnames</span>(df)<span class="op">==</span><span class="st">&quot;d10&quot;</span>] &lt;-<span class="st"> &quot;gender&quot;</span></a></code></pre></div>
<p>If you prefer the <em>tydiverse</em> dialect (that aims to save you typing among other things), then you would use the <code>rename</code> function as below (beware if you already renamed <em>d10</em> using <code>colnames</code> there will be no longer a <em>d10</em> variable and therefore R will return an error).</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb236-1" title="1">df &lt;-<span class="st"> </span><span class="kw">rename</span>(df, <span class="dt">gender=</span>d10)</a></code></pre></div>
<p>If you now check the names of the variables (with the <code>names</code> function) in <code>df</code> you will see what has happened:</p>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb237-1" title="1"><span class="kw">names</span>(df)</a></code></pre></div>
<pre><code>##  [1] &quot;uniqid&quot;     &quot;qb10_1&quot;     &quot;qb10_2&quot;     &quot;qb10_3&quot;     &quot;qb10_4&quot;    
##  [6] &quot;qb10_5&quot;     &quot;qb10_6&quot;     &quot;qb10_7&quot;     &quot;qb10_8&quot;     &quot;qb10_9&quot;    
## [11] &quot;qb10_10&quot;    &quot;qb10_11&quot;    &quot;qb10_12&quot;    &quot;gender&quot;     &quot;d11&quot;       
## [16] &quot;isocntry&quot;   &quot;d1&quot;         &quot;d25&quot;        &quot;d15a&quot;       &quot;at_sexviol&quot;
## [21] &quot;region&quot;</code></pre>
<p>If you want to change many variable names it may be more efficient doing it all at once. First we are going to select fewer variables and retain only the ones will continue using:</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb239-1" title="1">df &lt;-<span class="st"> </span><span class="kw">select</span>(df, uniqid, at_sexviol, gender, d11, d1, d25, d15a, region)</a></code></pre></div>
<p>Now we can change a bunch of names all at once with the following code:</p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb240-1" title="1"><span class="kw">names</span>(df)[<span class="dv">4</span><span class="op">:</span><span class="dv">7</span>] &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;age&quot;</span>, <span class="st">&quot;politics&quot;</span>, <span class="st">&quot;urban&quot;</span>, <span class="st">&quot;occupation&quot;</span>)</a>
<a class="sourceLine" id="cb240-2" title="2"><span class="kw">names</span>(df)</a></code></pre></div>
<pre><code>## [1] &quot;uniqid&quot;     &quot;at_sexviol&quot; &quot;gender&quot;     &quot;age&quot;        &quot;politics&quot;  
## [6] &quot;urban&quot;      &quot;occupation&quot; &quot;region&quot;</code></pre>
<p>You may have seen we wrote <code>[4:7]</code> above. This square bracket notation is identifying the columns within that particular object. It is indicating to R that we only wanted to change the name of the variables defining column 4 to 7 in the dataframe, those corresponded to d11, d1, d25, and d15a, which respectively (we can see in the questionnaire) correspond to age, politics, whether the respondent live in a urban setting, and occupation. We assign to those columns the names we specify (in the appropriate order) in the list that follows. Now we will be less likely to confuse ourselves, since we have columns with meaningful names (which will appear in any output and plots we produce).</p>
<p>Let’s look at occupation:</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb242-1" title="1"><span class="kw">table</span>(df<span class="op">$</span>occupation)</a></code></pre></div>
<pre><code>## 
##    1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16 
## 1588 1864 1845 8916  129   14  384  768  517  878  313 1921 2202  856 2062  271 
##   17   18 
## 2471  819</code></pre>
<p>There are 18 categories here. And it is not clear what they mean.</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb244-1" title="1"><span class="kw">class</span>(df<span class="op">$</span>occupation)</a></code></pre></div>
<pre><code>## [1] &quot;haven_labelled&quot;</code></pre>
<p>Remember that this is <code>haven_labelled</code>. If we look at the attributes we can see the correspondence between the numbers above and the labels.</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb246-1" title="1"><span class="kw">attributes</span>(df<span class="op">$</span>occupation)</a></code></pre></div>
<pre><code>## $label
## [1] &quot;OCCUPATION OF RESPONDENT&quot;
## 
## $format.stata
## [1] &quot;%8.0g&quot;
## 
## $class
## [1] &quot;haven_labelled&quot;
## 
## $labels
##       Responsible for ordinary shopping, etc. 
##                                             1 
##                                       Student 
##                                             2 
##           Unemployed, temporarily not working 
##                                             3 
##                       Retired, unable to work 
##                                             4 
##                                        Farmer 
##                                             5 
##                                     Fisherman 
##                                             6 
##                   Professional (lawyer, etc.) 
##                                             7 
##              Owner of a shop, craftsmen, etc. 
##                                             8 
##                    Business proprietors, etc. 
##                                             9 
## Employed professional (employed doctor, etc.) 
##                                            10 
##                      General management, etc. 
##                                            11 
##                       Middle management, etc. 
##                                            12 
##                    Employed position, at desk 
##                                            13 
##                 Employed position, travelling 
##                                            14 
##                Employed position, service job 
##                                            15 
##                                    Supervisor 
##                                            16 
##                         Skilled manual worker 
##                                            17 
##                 Unskilled manual worker, etc. 
##                                            18</code></pre>
<p>Having to look at this every time is not very convenient. You may prefer to simply use the labels directly. For this we can use the <code>to_factor</code> function from the <code>labelled</code> package.</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb248-1" title="1"><span class="kw">library</span>(labelled)</a>
<a class="sourceLine" id="cb248-2" title="2">df<span class="op">$</span>f_occup &lt;-<span class="st"> </span><span class="kw">to_factor</span>(df<span class="op">$</span>occupation)</a>
<a class="sourceLine" id="cb248-3" title="3"><span class="kw">class</span>(df<span class="op">$</span>f_occup)</a></code></pre></div>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb250-1" title="1"><span class="kw">table</span>(df<span class="op">$</span>f_occup)</a></code></pre></div>
<pre><code>## 
##       Responsible for ordinary shopping, etc. 
##                                          1588 
##                                       Student 
##                                          1864 
##           Unemployed, temporarily not working 
##                                          1845 
##                       Retired, unable to work 
##                                          8916 
##                                        Farmer 
##                                           129 
##                                     Fisherman 
##                                            14 
##                   Professional (lawyer, etc.) 
##                                           384 
##              Owner of a shop, craftsmen, etc. 
##                                           768 
##                    Business proprietors, etc. 
##                                           517 
## Employed professional (employed doctor, etc.) 
##                                           878 
##                      General management, etc. 
##                                           313 
##                       Middle management, etc. 
##                                          1921 
##                    Employed position, at desk 
##                                          2202 
##                 Employed position, travelling 
##                                           856 
##                Employed position, service job 
##                                          2062 
##                                    Supervisor 
##                                           271 
##                         Skilled manual worker 
##                                          2471 
##                 Unskilled manual worker, etc. 
##                                           819</code></pre>
<p>Now you have easier to interpret output.</p>
</div>
<div id="recoding-factors" class="section level2">
<h2><span class="header-section-number">4.8</span> Recoding factors</h2>
<p>As we said there are many different types of objects in R and depending on their nature the recoding procedures may vary. You may remember that many times categorical variables will be encoded as factors. Let’s go back our newly created <em>f_occup</em>. We have 18 categories here. These are possibly too many. Some of them have to few cases, like <em>fisherman</em>. Although this is a fairly large dataset we only have 14 fisherman. It would be a bit brave to guess what fishermen across Europe think about sexual violence based in a sample of just 14 of them.</p>
<p>This is a very common scenario when you analyse data. In these cases is helpful to think of ways of adding the groups with small counts (like fishermen in this case) to a broader but still meaningful category. People often refer to this as <em>collapsing categories</em>. You also have to think theoretically, do you have good enough reasons to think that there’s ought to be meaningful differences in attitudes to sexual violence among these 18 groups? If you don’t you may want to collapse into fewer categories that may make more sense.</p>
<p>As when we created the <em>region</em> variable the first thing to do is to come out with a new coding scheme for this variable. We are going to use the following. I’m not making this scheme up, I am just using the scheme that the Eubarometer uses to simplify these categories.</p>
<pre><code>1   Self-employed (5 to 9 in d15a)  
2   Managers (10 to 12 in d15a) 
3   Other white collars (13 or 14 in d15a)  
4   Manual workers (15 to 18 in d15a)   
5   House persons (1 in d15a)   
6   Unemployed (3 in d15a)  
7   Retired (4 in d15a) 
8   Students (2 in d15a)</code></pre>
<p>It would be quicker to recode from <em>d15a</em> into a new variable (there would be less typing when dealing with numbers rather than labels). But here we are going to use this example to show you how to recode from a factor variable, so instead we will recode form <em>f_occup</em>.</p>
<p>As often in R, there are multiple ways of doing this. We could use <code>dplyr::recode</code>. But here we will show you how to do this using the <code>recode</code> function from the <code>car</code> library.</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb253-1" title="1">df<span class="op">$</span>occup2 &lt;-<span class="st"> </span>df<span class="op">$</span>f_occup</a>
<a class="sourceLine" id="cb253-2" title="2"><span class="kw">levels</span>(df<span class="op">$</span>occup2) &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="st">&quot;Self-employed&quot;</span> =<span class="st"> </span></a>
<a class="sourceLine" id="cb253-3" title="3"><span class="st">                            </span><span class="kw">c</span>(<span class="st">&quot;Farmer&quot;</span> , <span class="st">&quot;Fisherman&quot;</span> ,</a>
<a class="sourceLine" id="cb253-4" title="4">                              <span class="st">&quot;Professional (lawyer, etc.)&quot;</span> ,</a>
<a class="sourceLine" id="cb253-5" title="5">                              <span class="st">&quot;Owner of a shop, craftsmen, etc.&quot;</span>,</a>
<a class="sourceLine" id="cb253-6" title="6">                              <span class="st">&quot;Business proprietors, etc.&quot;</span>),</a>
<a class="sourceLine" id="cb253-7" title="7">                          <span class="st">&quot;Managers&quot;</span> =<span class="st"> </span></a>
<a class="sourceLine" id="cb253-8" title="8"><span class="st">                            </span><span class="kw">c</span>(<span class="st">&quot;Employed professional (employed doctor, etc.)&quot;</span>,</a>
<a class="sourceLine" id="cb253-9" title="9">                              <span class="st">&quot;General management, etc.&quot;</span>, </a>
<a class="sourceLine" id="cb253-10" title="10">                              <span class="st">&quot;Middle management, etc.&quot;</span>),</a>
<a class="sourceLine" id="cb253-11" title="11">                          <span class="st">&quot;Other white collar&quot;</span> =<span class="st"> </span></a>
<a class="sourceLine" id="cb253-12" title="12"><span class="st">                            </span><span class="kw">c</span>(<span class="st">&quot;Employed position, at desk&quot;</span>, </a>
<a class="sourceLine" id="cb253-13" title="13">                              <span class="st">&quot;Employed position, travelling&quot;</span>),</a>
<a class="sourceLine" id="cb253-14" title="14">                          <span class="st">&quot;Manual workers&quot;</span> =<span class="st"> </span></a>
<a class="sourceLine" id="cb253-15" title="15"><span class="st">                            </span><span class="kw">c</span>(<span class="st">&quot;Employed position, service job&quot;</span>,</a>
<a class="sourceLine" id="cb253-16" title="16">                              <span class="st">&quot;Supervisor&quot;</span>,</a>
<a class="sourceLine" id="cb253-17" title="17">                              <span class="st">&quot;Skilled manual worker&quot;</span>,</a>
<a class="sourceLine" id="cb253-18" title="18">                              <span class="st">&quot;Unskilled manual worker, etc.&quot;</span>),</a>
<a class="sourceLine" id="cb253-19" title="19">                          <span class="st">&quot;House persons&quot;</span> =<span class="st"> &quot;Responsible for ordinary shopping, etc.&quot;</span>,</a>
<a class="sourceLine" id="cb253-20" title="20">                          <span class="st">&quot;Unemployed&quot;</span> =<span class="st"> &quot;Unemployed, temporarily not working&quot;</span>,</a>
<a class="sourceLine" id="cb253-21" title="21">                          <span class="st">&quot;Retired&quot;</span> =<span class="st">  &quot;Retired, unable to work&quot;</span>,</a>
<a class="sourceLine" id="cb253-22" title="22">                          <span class="st">&quot;Student&quot;</span> =<span class="st"> &quot;Student&quot;</span>)</a></code></pre></div>
<p>One of the things you need to be very careful with when recoding factors or character variables is that you need to input the chunk of texts in the existing variables exactly as they appear in the variable. Otherwise you will get into trouble. So, for example, if in the code above you wrote <code>fishermen</code> instead of <code>Fisherman</code> you would have 14 less cases in the <code>Self-Employed</code> level than you should have. When doing this kind of operations is always convenient to check that the categories add up correctly.</p>
<p>For more details in how to recode factors and other potential scenarios you may want to read <a href="https://peerj.com/preprints/3163/">this paper</a> by Amelia McNamara and Nicholas Horton.</p>
</div>
<div id="understanding-missing-data" class="section level2">
<h2><span class="header-section-number">4.9</span> Understanding missing data</h2>
<p>As we have already seen, you will have participants that do not provide you with valid answers for the questions in the survey. In general in any kind of data set you work with, whether it comes from surveys or not, you will have cases for which you won’t have valid information for particular variables in your dataframe. Missing data is common.</p>
<p>Let’s look at the <em>politics</em> variable.</p>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb254-1" title="1"><span class="kw">class</span>(df<span class="op">$</span>politics)</a></code></pre></div>
<pre><code>## [1] &quot;haven_labelled&quot;</code></pre>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb256-1" title="1"><span class="kw">table</span>(df<span class="op">$</span>politics)</a></code></pre></div>
<pre><code>## 
##    1    2    3    4    5    6    7    8    9   10   97   98 
## 1433  830 2161 2217 6690 2238 2056 1658  474 1126 2766 4169</code></pre>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb258-1" title="1"><span class="kw">sum</span>(<span class="kw">is.na</span>(df<span class="op">$</span>politics))</a></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>It looks as if we have no missing data. Right? Well, appearances can be deceiving sometimes.</p>
<p><img src="imgs/leftright.PNG" /></p>
<p>This is the question as it was asked from the survey respondents. Notice the difference in the response options and the categories in <em>politics</em>. We know that those that see themselves further to the left will have answer 1 and those that see themselves further to the right would have answer 10. What does 97 and 98 then refers to? If you look at the questionnaire you will see that those that refuse or don’t know <em>in the questionnaire</em> are coded as 11 and 12.</p>
<p>Let’s look closer at the <code>attributes</code>:</p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb260-1" title="1"><span class="kw">attributes</span>(df<span class="op">$</span>politics)</a></code></pre></div>
<pre><code>## $label
## [1] &quot;LEFT-RIGHT PLACEMENT&quot;
## 
## $format.stata
## [1] &quot;%8.0g&quot;
## 
## $class
## [1] &quot;haven_labelled&quot;
## 
## $labels
##   Box 1 - left          Box 2          Box 3          Box 4          Box 5 
##              1              2              3              4              5 
##          Box 6          Box 7          Box 8          Box 9 Box 10 - right 
##              6              7              8              9             10 
##        Refusal             DK 
##             97             98</code></pre>
<p>A tip if you don’t want to see as much output. If you want to access directly only some of the attributes you can call them directly modifying the code as below:</p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb262-1" title="1"><span class="kw">attributes</span>(df<span class="op">$</span>politics)<span class="op">$</span>labels</a></code></pre></div>
<pre><code>##   Box 1 - left          Box 2          Box 3          Box 4          Box 5 
##              1              2              3              4              5 
##          Box 6          Box 7          Box 8          Box 9 Box 10 - right 
##              6              7              8              9             10 
##        Refusal             DK 
##             97             98</code></pre>
<p>Or we could use the <code>val_labels</code> function from the <code>labelled</code> package for the same result:</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb264-1" title="1"><span class="kw">val_labels</span>(df<span class="op">$</span>politics)</a></code></pre></div>
<pre><code>##   Box 1 - left          Box 2          Box 3          Box 4          Box 5 
##              1              2              3              4              5 
##          Box 6          Box 7          Box 8          Box 9 Box 10 - right 
##              6              7              8              9             10 
##        Refusal             DK 
##             97             98</code></pre>
<p>Notice that though the questionnaire assigned a value of 11 to refusal and 12 to “don’t know” answers, in the dataset those values are instead 97 and 98. You will see this often - 97, 98, 99, and similar codes are often used to denote missing data.</p>
<p>You may have good theoretical reasons to preserve this in your analysis. Perhaps you think that people that did not answer this question have particular reasons not to do so and those reasons may be associated with their attitudes to violence. In that case you may want to somehow preserve them in your analysis. Absent that rationale you may just want to treat them as they are: missing data. You just have no way of knowing if these people are more or less lefty or conservative. So let’s declare them as such for sake of explaining how you would do that:</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb266-1" title="1">df<span class="op">$</span>politics[df<span class="op">$</span>politics<span class="op">&gt;=</span><span class="dv">97</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></a>
<a class="sourceLine" id="cb266-2" title="2"><span class="kw">table</span>(df<span class="op">$</span>politics)</a></code></pre></div>
<pre><code>## 
##    1    2    3    4    5    6    7    8    9   10 
## 1433  830 2161 2217 6690 2238 2056 1658  474 1126</code></pre>
<p>The equal or greater operator in R is written as <code>&gt;=</code>. What we are saying in the first statement to R is that whenever <em>politics</em> has a value equal or greater than 97 we are going to recode those cases as <code>NA</code>, as missing data. Since this is a <code>haven_labelled</code> vector we can use numbers here rather than characters or factor levels as part of the recoding. That makes things a bit easier in that it saves typing.
Let’s look a the results:</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb268-1" title="1"><span class="kw">summary</span>(df<span class="op">$</span>politics)</a></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   1.000   4.000   5.000   5.196   7.000  10.000    6935</code></pre>
<p>Now you see you have 6935 cases with missing data. As always it is good to check the original variable. We had 2766 and 4169 between refusals and “don’t know” respondents. These add up to 6935.</p>
<p>Let’s check something else:</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb270-1" title="1"><span class="kw">library</span>(skimr)</a>
<a class="sourceLine" id="cb270-2" title="2"><span class="kw">skim</span>(df<span class="op">$</span>politics)</a></code></pre></div>
<p>Mmmmm. The <code>summary</code> function worked, but other functions do not know to treat the values in the <code>haven_labelled</code> vector as a numeric. So, to avoid problems we may want to define as such (if we truly believe this is a quantitative rather than a categorical variable or at the very least are willing to treat it as quantitative).</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb271-1" title="1">df<span class="op">$</span>politics_n &lt;-<span class="kw">as.numeric</span>(df<span class="op">$</span>politics)</a></code></pre></div>
<p>If you try this now, you will see it works:</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb272-1" title="1"><span class="kw">skim</span>(df<span class="op">$</span>politics_n)</a></code></pre></div>
<p>If we want to see what percentage of cases is NA across our dataset we could use <code>colMeans</code> combined with <code>is.na</code>. This will compute the mean (the proportion) of cases that are NA in each of the columns of the dataframe:</p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb273-1" title="1"><span class="kw">colMeans</span>(<span class="kw">is.na</span>(df))</a></code></pre></div>
<pre><code>##     uniqid at_sexviol     gender        age   politics      urban occupation 
## 0.00000000 0.04540226 0.00000000 0.00000000 0.24929902 0.00000000 0.00000000 
##     region    f_occup     occup2 politics_n 
## 0.00000000 0.00000000 0.00000000 0.24929902</code></pre>
<p>This is suspicious. Only the variables we have created and already sorted seem to have NA. This may be a function of the <code>haven_labelled</code> vectors behaving like with the original <em>politics</em> variable. Let’s explore it. We can use the <code>val_labels</code> function from the <code>labelled</code> package to extract labels from the whole dataframe like this:</p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb275-1" title="1"><span class="kw">val_labels</span>(df)</a></code></pre></div>
<pre><code>## $uniqid
## NULL
## 
## $at_sexviol
## Not mentioned     Mentioned 
##             0             1 
## 
## $gender
##   Man Woman 
##     1     2 
## 
## $age
##                      15 years                      96 years 
##                            15                            96 
## 99 and older [not documented] 
##                            99 
## 
## $politics
##   Box 1 - left          Box 2          Box 3          Box 4          Box 5 
##              1              2              3              4              5 
##          Box 6          Box 7          Box 8          Box 9 Box 10 - right 
##              6              7              8              9             10 
##        Refusal             DK 
##             97             98 
## 
## $urban
## Rural area or village     Small/middle town            Large town 
##                     1                     2                     3 
##                    DK 
##                     8 
## 
## $occupation
##       Responsible for ordinary shopping, etc. 
##                                             1 
##                                       Student 
##                                             2 
##           Unemployed, temporarily not working 
##                                             3 
##                       Retired, unable to work 
##                                             4 
##                                        Farmer 
##                                             5 
##                                     Fisherman 
##                                             6 
##                   Professional (lawyer, etc.) 
##                                             7 
##              Owner of a shop, craftsmen, etc. 
##                                             8 
##                    Business proprietors, etc. 
##                                             9 
## Employed professional (employed doctor, etc.) 
##                                            10 
##                      General management, etc. 
##                                            11 
##                       Middle management, etc. 
##                                            12 
##                    Employed position, at desk 
##                                            13 
##                 Employed position, travelling 
##                                            14 
##                Employed position, service job 
##                                            15 
##                                    Supervisor 
##                                            16 
##                         Skilled manual worker 
##                                            17 
##                 Unskilled manual worker, etc. 
##                                            18 
## 
## $region
## NULL
## 
## $f_occup
## NULL
## 
## $occup2
## NULL
## 
## $politics_n
## NULL</code></pre>
<p>Notice that in <em>urban</em> there are explicit codes for missing data but that these values won’t be treated as such, at least we do something. Let’s see how many cases we have in this scenario:</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb277-1" title="1"><span class="kw">table</span>(df<span class="op">$</span>urban)</a></code></pre></div>
<pre><code>## 
##     1     2     3     8 
##  8563 11881  7356    18</code></pre>
<p>Not too bad. Let’s sort this variable:</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb279-1" title="1">df<span class="op">$</span>urban[df<span class="op">$</span>urban<span class="op">&gt;=</span><span class="dv">8</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></a>
<a class="sourceLine" id="cb279-2" title="2">df<span class="op">$</span>f_urban &lt;-<span class="st"> </span><span class="kw">to_factor</span>(df<span class="op">$</span>urban)</a>
<a class="sourceLine" id="cb279-3" title="3"><span class="kw">table</span>(df<span class="op">$</span>f_urban)</a></code></pre></div>
<pre><code>## 
## Rural area or village     Small/middle town            Large town 
##                  8563                 11881                  7356 
##                    DK 
##                     0</code></pre>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb281-1" title="1"><span class="kw">mean</span>(<span class="kw">is.na</span>(df<span class="op">$</span>f_urban))</a></code></pre></div>
<pre><code>## [1] 0.0006470631</code></pre>
<p>You can see that even though have now no cases with a value of 8 or DK, the label appears printed in the output. This is still a valid level:</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb283-1" title="1"><span class="kw">levels</span>(df<span class="op">$</span>f_urban)</a></code></pre></div>
<pre><code>## [1] &quot;Rural area or village&quot; &quot;Small/middle town&quot;     &quot;Large town&quot;           
## [4] &quot;DK&quot;</code></pre>
<p>So, we may want to remove it explicitly if we don’t want output reminding us what we already know, that “there are not” DK cases (since now we call them and treat them as NA). For removing unused levels in a factor we use the <code>droplevels</code> function,</p>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb285-1" title="1">df<span class="op">$</span>f_urban &lt;-<span class="st"> </span><span class="kw">droplevels</span>(df<span class="op">$</span>f_urban)</a>
<a class="sourceLine" id="cb285-2" title="2"><span class="kw">table</span>(df<span class="op">$</span>f_urban)</a></code></pre></div>
<pre><code>## 
## Rural area or village     Small/middle town            Large town 
##                  8563                 11881                  7356</code></pre>
<p>Above also saw the codes for <em>gender</em> let’s use <code>to_factor</code> again for this variable:</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb287-1" title="1">df<span class="op">$</span>f_gender &lt;-<span class="st"> </span><span class="kw">to_factor</span>(df<span class="op">$</span>gender)</a></code></pre></div>
<p>Let’s just keep the variables we will retain for our final analysis:</p>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb288-1" title="1">df_f &lt;-<span class="st"> </span><span class="kw">select</span>(df, uniqid, at_sexviol, f_gender, age, politics_n,</a>
<a class="sourceLine" id="cb288-2" title="2">               f_urban, f_occup, region)</a></code></pre></div>
<p>We are going to do some further exploration of NA. Let’s create a new variable that identifies the cases that have missing data in at least one of the columns in the data with the final variables for our analysis. For this we can use the <code>complete.cases</code> function that creates a logical vector indicating whether any of the cases has missing values in at least one column:</p>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb289-1" title="1">df_f<span class="op">$</span>complete &lt;-<span class="st"> </span><span class="kw">complete.cases</span>((df_f))</a>
<a class="sourceLine" id="cb289-2" title="2"><span class="kw">table</span>(df_f<span class="op">$</span>complete)</a></code></pre></div>
<pre><code>## 
## FALSE  TRUE 
##  7634 20184</code></pre>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb291-1" title="1"><span class="kw">mean</span>(df_f<span class="op">$</span>complete)</a></code></pre></div>
<pre><code>## [1] 0.7255734</code></pre>
<p>So, shocking as this may sound you only have full data in 72% of the participants. Notice how the percentage of missing cases in the variables range:</p>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb293-1" title="1"><span class="kw">colMeans</span>(<span class="kw">is.na</span>(df_f))</a></code></pre></div>
<pre><code>##       uniqid   at_sexviol     f_gender          age   politics_n      f_urban 
## 0.0000000000 0.0454022575 0.0000000000 0.0000000000 0.2492990150 0.0006470631 
##      f_occup       region     complete 
## 0.0000000000 0.0000000000 0.0000000000</code></pre>
<p>The function <code>complete.cases</code> is returning what cases have missing data <strong>in any of</strong> the variables not in a singular one. It is not unusual for this percentage to be high. You may end up with a massive loss of cases even though the individual variables themselves do not look as bad as the end scenario.</p>
<p>Later this term we will cover forms of analysis (e.g., multiple regression) in which you have to work with multiple variables at the same time. This form of analysis require you to have information for all the cases and all the variables. Every case for which there is not information in one of the variables in your analysis is automatically excluded from such analysis. So the actual sample size you use when using these techniques is the sample size for which you have full information. In our example your sample size (when you do multiple regression analysis or any multivariate analysis) will be 20184 rather than 27818.</p>
<p>This being the case it makes sense to exclude from your data all cases that have some missing information in the variables you will be using in your analisis. For this you can use the <code>na.omit</code> function. We create a new object (I name it “full_df”, you can call it whatever) and put inside it the outcome of running <code>na.omit</code> in our original sample (“df_f”).</p>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb295-1" title="1">full_df &lt;-<span class="st"> </span><span class="kw">na.omit</span>(df_f)</a></code></pre></div>
<p>Now we have a dataset ready for starting our analysis. This is the point, when you are doing your assignment, that you can start running frequency distributions that you will report, and all kinds of statistical tests that we cover in the weeks to come.</p>
</div>
<div id="exploring-dataframes-visually" class="section level2">
<h2><span class="header-section-number">4.10</span> Exploring dataframes visually</h2>
<p>We have covered now a number of functions you can use to explore your data, such as <code>skimr::skim()</code>, <code>str()</code>, <code>summary()</code>, <code>table()</code>, or <code>dplyr::glimpse()</code>. But sometimes is useful to get a more panoramic way. For this we can use the <code>visdat</code> package for visualising whole dataframes amd its main function <code>vis_dat()</code>.</p>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb296-1" title="1"><span class="kw">library</span>(visdat)</a>
<a class="sourceLine" id="cb296-2" title="2"><span class="kw">vis_dat</span>(df_f)</a></code></pre></div>
<p><img src="04-carpentry_files/figure-html/unnamed-chunk-52-1.png" width="672" /></p>
<p>Nice one! You get a visual representations of how your variables are encoded in this dataframe. You have several categorical variables such as region, f_gender, f_urban, and f_occup. We see that region is encoded as a <code>character</code> vector, whereas the others are <code>factors</code>. For the purposes of this course, it is generally better to have your categorical variables encoded as factors. So one of the next steps in our data prep may be to recode region as a factor.</p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb297-1" title="1">df_f<span class="op">$</span>f_region &lt;-<span class="st"> </span><span class="kw">as.factor</span>(df_f<span class="op">$</span>region)</a></code></pre></div>
<p>We can also see we have age, a quantitative variable, <em>age</em>, encoded as <code>haven_labelled</code>. We could as well encoded as <code>numeric</code>.</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb298-1" title="1">df_f<span class="op">$</span>age &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(df_f<span class="op">$</span>age)</a></code></pre></div>
<p>What we do with <em>at_sexviol</em> depends on how we decide to treat it. But for arguments sake let’s say we are going to treat it as numerical.</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb299-1" title="1">df_f<span class="op">$</span>at_sexviol &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(df_f<span class="op">$</span>at_sexviol)</a></code></pre></div>
<p>The othe piece of info you get with <code>vis_dat</code> is the prevalence of missing data (NA) for each variable (the dark horizontal cases represent a missing case in the variable). We can summarise missing data visually more clearly with <code>vis_miss</code>.</p>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb300-1" title="1"><span class="kw">vis_miss</span>(df_f)</a></code></pre></div>
<p><img src="04-carpentry_files/figure-html/unnamed-chunk-56-1.png" width="672" /></p>
<p>You can find more details about how to explore missing data in the vignette of the <code>naniar</code> package <a href="http://naniar.njtierney.com/articles/getting-started-w-naniar.html">here</a>.</p>
<p><strong>Homework 4.3:</strong>
<em>Select the key outcome variable from the data set you have selected for your final assignment. By outcome variable we mean the variable or variables that tap into the concept you will be exploring with this assignment. In the practical today that was attitudes toward sexual violence. For your assignment it will be one of the four topics you selected in previous weeks. You need to look at the dataset screen the questions that tap into this concept and select a few you may want to explore before making a final decision as to whicn you will be using for sure. Do any recoding you may need to this variable (including creating summated scales or collapsing variables if it seems appropriate) and produce descriptive and visual analysis of this variable/s.</em></p>
</div>
<div id="further-resources" class="section level2">
<h2><span class="header-section-number">4.11</span> Further resources</h2>
<p>There are many other ways to recode variables and create new variables based in existing ones. Here we only provided some examples. We cannot exhaust all possibilities in this tutorial. For the purposes of the assignment you may have specific ideas of how you may want to combine variables or recode existing ones. You can find additional examples and code for how to do the recoding of variables in the following links. Please make sure that you spend some time looking at these additional resources. They are not optional.</p>
<p><a href="https://peerj.com/preprints/3163.pdf">Wrangling categorical data in R</a></p>
<p><a href="http://rprogramming.net/recode-data-in-r/">http://rprogramming.net/recode-data-in-r/</a></p>
<p><a href="http://www.cookbook-r.com/Manipulating_data/Recoding_data/">http://www.cookbook-r.com/Manipulating_data/Recoding_data/</a></p>
<p><a href="https://mgimond.github.io/ES218/Week03a.html">https://mgimond.github.io/ES218/Week03a.html</a></p>
<p><a href="https://www.r-bloggers.com/from-continuous-to-categorical/">https://www.r-bloggers.com/from-continuous-to-categorical/</a></p>
<p>You should also look for the <code>dplyr</code> documentation for the functions mutate() and recode().</p>
<p>If you would like to combine several variables into one for your analysis in more complex ways but do not know how to do that, please do get in touch. Also do not hesitate to approach us if you have any other specific queries.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-visualisation-with-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="foundations-of-statistical-inference-confidence-intervals.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["book.pdf", "book.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
